web/index.ts
Add the headers for the relevant URLs for deployment. Also add the new planned dashboard URLs.
=> Add CORS headers for production, resolve #8

common/transactionlog/types/CreateCourseEvent.ts, common/transactionlog/types/CreatedCourseEvent.ts, common/transactionlog/types/LogType.ts, common/transactionlog/types/LogUserEvent.ts, common/transactionlog/types/UpdateStudentDescriptionEvent.ts
=> Extend TransactionLog

web/controllers/userController/format.ts, web/controllers/userController/index.ts
=> Add date field to Match Object

web/controllers/userController/format.ts, web/controllers/userController/index.ts, web/index.ts
=> Implement PUT /user/:id/description

web/controllers/courseController/format.ts, web/controllers/courseController/index.ts
=> Route GET /courses

web/controllers/courseController/format.ts, web/controllers/courseController/index.ts
=> POST /course

common/entity/Pupil.ts, common/entity/Student.ts, common/migration/1590974746793-screening-reminder-matching-priorities.ts
This pull request will add all required database fields and migration files to fulfill/close #26.
=> #26 Required database fields for screening reminders and matching priorities

common/entity/Course.ts, common/entity/Lecture.ts, common/entity/Subcourse.ts, web/controllers/courseController/format.ts, web/controllers/courseController/index.ts, web/dev.ts, web/index.ts
=> Implement Course Controller

common/entity/Student.ts, jobs/backend/fetch/index.ts, web/controllers/registrationController/format.ts, web/controllers/registrationController/index.ts, web/index.ts
=> Add registration for pupils and instructors

common/entity/Subcourse.ts, web/controllers/courseController/format.ts, web/controllers/courseController/index.ts, web/index.ts
=> Course Join/Leave

web/controllers/certificateController/index.ts, web/controllers/tokenController/index.ts, web/dev.ts
Fixes things I've came across while building the dev-env:
(1) The latest tsc fails to compile without the typecasts, so adding them was the easiest fix
(2) A testuser for screening would be quite useful, thus a proper hashed password has to be set.
=> Fix types and screener testuser password

common/entity/Student.ts, common/migration/1592228468303-AddTutorOtherModule.ts, web/controllers/registrationController/index.ts
Resolve #58 by adding module = "other" for Tutor registration.
=> Update tutor registration

common/entity/InstructorScreening.ts, common/entity/Student.ts, common/migration/1592477604748-AddInstructorScreening.ts
=> Add instructor screening entities

web/dev.ts
=> Add Dummy Data for Courses

web/controllers/userController/format.ts, web/controllers/userController/index.ts
Past matches certificate generation #75
=> Past matches certificate generation #75

web/controllers/registrationController/index.ts
=> Fix default subjects

web/controllers/userController/format.ts, web/controllers/userController/index.ts
=> Add instructor screening status to getUser API, resolve #89

common/administration/screening/initial-invitations/index.ts, common/entity/Student.ts, common/mails/screening/index.ts, common/mails/templates.ts, web/controllers/tokenController/index.ts
This adds the instructor screening invitation which overrides the normal invitation if a user registered as an instructor.
=> Add instructor screening invitations

common/entity/Student.ts, web/controllers/registrationController/format.ts, web/controllers/registrationController/index.ts, web/controllers/userController/format.ts, web/controllers/userController/index.ts
This updates the role update routes to include isOfficial parameters for Interns.
Also fixing some apidocs.
=> Updates to role change for instructor

web/controllers/registrationController/format.ts, web/controllers/registrationController/index.ts, web/controllers/userController/format.ts, web/controllers/userController/index.ts
This adds the state selection to routes for instructor + intern registration and role changes.
=> Add state to intern role

common/dto/ApiCourseUpdate.ts, common/entity/Course.ts, web/controllers/screeningController/index.ts
Enables editing course instructors for screeners.
=> Support course instructor updates

jobs/periodic/fetch/utils/verification/index.ts, web/controllers/registrationController/format.ts, web/controllers/registrationController/index.ts
Can't test locally though, let's test in dev.
=> Add redirectTo parameter to registration, and pass it on with verify link

common/entity/Subcourse.ts, web/controllers/screeningController/index.ts
This is the backend part necessary for editing course date and times during course update as a screener. This is realized by adding or removing lectures respectively.
=> [#173] Administrator edit course date and time

app.json, package-lock.json, package.json, tests/utils/typeorm.ts, web/controllers/screeningController/index.ts
When searching for courses, search case insensitive, also allow searching by user
Resolves https://github.com/corona-school/project-user/issues/210
resolves https://github.com/corona-school/project-user/issues/209
TODO:
=> Add improved search and pagination to course screening

common/entity/Course.ts, common/entity/Person.ts, common/entity/Pupil.ts, common/entity/Student.ts, common/entity/Subcourse.ts, common/mails/courses/index.ts, common/mails/index.ts, common/mails/templates.ts, common/migration/1610331307189-DrehtuerSprint2.ts, common/transactionlog/types/AccessedCourseEvent.ts, common/transactionlog/types/LogType.ts, common/transactionlog/types/ParticipantJoinedCourseEvent.ts, common/transactionlog/types/ParticipantJoinedWaitingListEvent.ts, common/transactionlog/types/ParticipantLeftCourseEvent.ts, common/transactionlog/types/ParticipantLeftWaitingListEvent.ts, package-lock.json, package.json, web/controllers/courseController/format.ts, web/controllers/courseController/index.ts, web/dev.ts, web/index.ts, web/middleware/auth.ts
This pull request will add the necessary backend changes to support all features of [Sprint 2 for the "Digitale Drehtür"](https://github.com/corona-school/project-user/milestone/7).
=> Drehtür Sprint 2

common/entity/Course.ts, common/entity/CourseGuest.ts, common/entity/Student.ts, common/mails/courses/index.ts, common/mails/templates.ts, common/migration/1610942251675-DrehtuerSprint3.ts, package-lock.json, package.json, web/controllers/courseController/format.ts, web/controllers/courseController/index.ts, web/index.ts
This pull request will add the necessary backend changes to support all features of [Sprint 3 for the "Digitale Drehtür"](https://github.com/corona-school/project-user/milestone/8).
Related to the changes: _I haven’t even tried to write proper documentation… It’s a mess…_
=> Drehtür Sprint 3

.gitignore, web/controllers/certificateController/index.ts, web/index.ts
Deploy together with https://github.com/corona-school/web-user-app/pull/135
=> Clean up the createSignature endpoint and make final adjustments for automatic signature process

common/google/index.ts, web/controllers/mentoringController/index.ts
Backend implementation for corona-school/project-user#283
=> Also retrieve title and description for peer to peer calls

web/controllers/registrationController/format.ts, web/controllers/registrationController/index.ts
Backend part of https://github.com/corona-school/project-user/issues/265
=> Setting open match request count to 0 for pupils if requestsAutoMatch is set to false

package-lock.json, package.json, web/controllers/registrationController/index.ts, web/index.ts
Incorporates changes from https://github.com/corona-school/backend/pull/182
+ rate-limiting
=> /register/checkEmail endpoint + rate-limiting

common/mentoring/categories.ts, web/controllers/mentoringController/index.ts
=> Added subject to mentoring contact emails

web/controllers/screeningController/index.ts
=> Added dupe check when editing email of student as a screener

web/controllers/userController/format.ts, web/controllers/userController/index.ts, web/dev.ts
Requirement for https://github.com/corona-school/project-user/issues/332
=> Added isOfficial  property to object /user/:id endpoint returns

web/controllers/courseController/index.ts, web/dev.ts
Increases course guest limit to 10 guests per course; as per https://github.com/corona-school/project-user/issues/333.
=> Increased course guest limit

common/mentoring/categories.ts
the email adress in the backend was wrong and should be now corrected
=> corrected mentoring mail-adresses

web/controllers/courseController/index.ts
As per https://github.com/corona-school/project-user/issues/294
=> Added limit of at least 5 days in advance for start date of lectures

web/controllers/courseController/format.ts, web/controllers/courseController/index.ts, web/dev.ts
As per https://github.com/corona-school/project-user/issues/284
=> Passing waiting list size in course request, added more pupils in dev.ts

web/controllers/userController/index.ts
Closes https://github.com/corona-school/project-user/issues/338
=> Now cancelling courses/removing student when student cancels their account

web/dev.ts
Clean up testemails, so that we can switch on sending out emails from dev.
=> Testemails

common/administration/match-making/tutoring/matches/notify/index.ts, common/administration/match-making/tutoring/matches/notify/mail.ts, common/entity/Notification.ts, common/match/create.ts, common/notification/ACTIONS.md, common/notification/index.ts, common/notification/types.ts, web/controllers/matchController/index.ts, web/dev.ts
c.f. https://github.com/corona-school/project-user/issues/414
=> Notification System touchups for match surveys

common/administration/match-making/tutoring/matches/notify/index.ts, common/administration/match-making/tutoring/matches/notify/mail.ts, common/match/create.ts, common/match/dissolve.ts, common/match/util.ts, common/notification/ACTIONS.md, web/controllers/matchController/index.ts
c.f. https://github.com/corona-school/project-user/issues/414
c.f. https://github.com/corona-school/project-user/issues/415
NOTE: Adjust Notifications during Deployment!
=> Adjustments for Match Survey Emails

common/notification/bulk.ts, common/notification/index.ts, common/notification/types.ts, graphql/index.ts, graphql/notification/fields.ts, graphql/notification/mutations.ts
[SQL Script for testing](https://github.com/corona-school/dev-db/blob/main/dev/SimulateMatche.pgsql)
Seems to work quite fine, I'll bulk test on DEV with some thousand matches.
=> Bulk Actions for newly introduced Notifications

graphql/course/mutations.ts
The follow up change you (@Jonasdoubleyou ) proposed. And I thought it would be nice to also return the course on the edit mutation (for caching?).
=> Update: Nullable types and return Course on edit instead of boolean

common/match/pool.ts, graphql/match_pool/fields.ts, graphql/match_pool/mutations.ts
Provides way to influence the behavior for Matching, with a flexible interface for different match pools
=> Match Pool toggling

common/secret/token.ts, integration-tests/auth.ts, integration-tests/base.ts, integration-tests/index.ts, integration-tests/matching.ts, integration-tests/user.ts, package-lock.json, package.json
IMO this adds way more coverage to our codebase as our implementations are rather "along workflows", thus creating unit tests is usually hard and adds little coverage. The integration tests cover less logic, however they at least ensure that nothing breaks in serious ways. 
I'm not quite sure how to integrate this into CI/CD as running those tests without a database / uplink is difficult. 
resolves https://github.com/corona-school/project-user/issues/447
=> [Draft] GraphQL Integration Tests

web/controllers/courseController/index.ts
resolves https://github.com/corona-school/project-user/issues/451
=> Block access to old courses

graphql/authentication.ts, graphql/index.ts, graphql/me/fields.ts, graphql/me/mutation.ts, graphql/pupil/fields.ts, graphql/student/fields.ts, graphql/user/fields.ts, graphql/user/mutations.ts
resolves https://github.com/corona-school/project-user/issues/438
=> Split up User and Me

graphql/index.ts, graphql/statistics/fields.ts
partially solves https://github.com/corona-school/project-user/issues/461
=> Statistics

graphql/me/fields.ts, graphql/ownership.ts, graphql/student/fields.ts, graphql/user/fields.ts
```
query { 
students(take: 10) { 
user { 
roles
}
canCreateCourse { allowed reason }
canRequestMatch { allowed reason }
tutorScreenings { id success comment }
instructorScreenings { id success comment }
}
myRoles
}
```
=> Queries for Support (Screenings, Roles, canCreateCourse)

graphql/certificate/mutations.ts, graphql/files.ts, web/controllers/fileController/index.ts, web/index.ts
resolves https://github.com/corona-school/project-user/issues/474
```
curl -F file=@somefile.txt https://api.corona-school.de/api/files/upload
curl https://api.corona-school.de/api/files/download/<the id> --output somefile.txt
```
=> Files for GraphQL

graphql/error.ts, graphql/index.ts, graphql/mentor/mutations.ts, graphql/types/enums.ts
Resolves https://github.com/corona-school/project-user/issues/478
```gql
mutation { 
mentoringContact(data: { 
subject: "Test",
message: "test",
category: LANGUAGE
})
}
```
=> Add mentoringContact Mutation

graphql/pupil/mutations.ts, graphql/student/mutations.ts, graphql/types/enums.ts, graphql/util.ts
Apollo seems to pass in undefined which works fine, but better not rely on that.
Also added state and schooltype as updateable fields
=> Fix updateStudent and updatePupil

common/entity/Course.ts, common/migration/1664805270024-IMPROVE_COURSES.ts, graphql/authorizations.ts, graphql/course/mutations.ts, package-lock.json, prisma/schema.prisma
See https://github.com/corona-school/project-user/issues/467.
=> Added subject and schooltype fields to courses

common/entity/Pupil.ts, common/entity/Student.ts, common/migration/1665846387535-AboutMe.ts, graphql/authorizations.ts, graphql/me/mutation.ts, graphql/pupil/mutations.ts, graphql/student/mutations.ts, prisma/schema.prisma
resolves https://github.com/corona-school/project-user/issues/482
=> Add aboutMe to Pupils and Students

graphql/authentication.ts, graphql/authorizations.ts, graphql/subcourse/fields.ts
New access Role: COURSE_PARTICIPANT
=> Add: subcourse.otherParticipants resolver

common/courses/states.ts, graphql/subcourse/fields.ts, graphql/subcourse/mutations.ts
Instead publishing is blocked. Also provide Subcourse.canPublish to check whether all requirements are met
=> Allow creation of Subcourses for not yet approved Courses

graphql/subcourse/fields.ts
Solves [project-user#489](https://github.com/corona-school/project-user/issues/489)
=> Add: aboutMe to participant and otherParticipant (subcourses)

common/match/pool.ts, graphql/match_pool/fields.ts
- Fix demand overprovisioning
- Expose whether match pool has interest confirmations
=> Fix interest confirmations

graphql/subcourse/fields.ts, graphql/subcourse/mutations.ts
- Added Subcourse.instructors
- subcourseCreate fix lectures
- Release subcourseJoinMeeting to pupils and fully implement
- excludeKnown arg for subcoursesPublic
=> Various course features

common/notification/hook.ts, graphql/student/fields.ts
resolves https://github.com/corona-school/project-user/issues/507
=> Predict date when an account will be deactivated due to missing CoC

common/secret/index.ts, graphql/types/enums.ts, graphql/user/mutations.ts
resolves https://github.com/corona-school/project-user/issues/508
=> Determine Login Options of User

common/secret/token.ts, web/index.ts
- Allow CORS from new productive User App
- Allow relative redirectTo URLs from User App
=> Adapt permissions for Frontend

graphql/concrete_notification/fields.ts
get concreteNotification by ID
=> extended concrete_notification resolver

common/courses/filters.ts, common/secret/token.ts, graphql/authentication.ts, graphql/pupil/fields.ts, graphql/student/fields.ts, graphql/subcourse/fields.ts, integration-tests/course.ts, integration-tests/index.ts, integration-tests/screening.ts, integration-tests/user.ts
resolves https://github.com/corona-school/project-user/issues/512
=> Course filters

common/websocket/index.ts
As it is not possible to set additional headers (like `Authorization`) when sending a ws connection request [1][2]. We are now sending the session token it as a query parameter as proposed by some developers [3][4].
May not be the best solution, but this should work for the beginning as query params are encrypted in ws request over TLS. 
[1] https://www.rfc-editor.org/rfc/rfc6455.html
[2] https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket#syntax
[3] https://github.com/whatwg/websockets/issues/16#issuecomment-347180825
[4] https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api
=> Websocket service auth with token as url parameter

graphql/pupil/mutations.ts
Added mutation for matchReason to updatePupil. This was missing in #382.
Closes https://github.com/corona-school/project-user/issues/490#issuecomment-1319845436
=> Added mutation for matchReason to updatePupil

common/notification/channels/inapp.ts, common/notification/channels/mailjet.ts, common/notification/index.ts, common/notification/types.ts, common/user/roles.ts, common/user/session.ts, common/websocket/index.ts, graphql/authentication.ts, graphql/roles.ts
added a new channel for `inapp` messages.
_fails for now by `npm run web`_  (@Jonasdoubleyou, @timidak )
=> In app channel

graphql/course/mutations.ts
=> Subject and schooltype can be omitted when creating a course

common/notification/types.ts, common/user/index.ts, graphql/subcourse/mutations.ts
... thus making a lot of USER released GraphQL stuff usable for screeners
=> Support Screeners in the Notification System

graphql/authentication.ts, graphql/index.ts, graphql/me/mutation.ts, graphql/school/fields.ts, graphql/screener/mutations.ts, graphql/secret/mutation.ts, graphql/subcourse/mutations.ts, graphql/user/mutations.ts, graphql/validators.ts, integration-tests/auth.ts, integration-tests/user.ts
resolves https://github.com/corona-school/project-user/issues/519
=> Email normalization

common/util/bbb.ts, jobs/list.ts, jobs/manualExecution.ts, jobs/periodic/anonymise-attendance-log/index.ts
Resolving Issue: corona-school/project-user#505
Not tested and not sure how I should reset the pupilID.
And anonymsing the transaction log seems quite cumbersome, because as far as I could understand it, the courseAttendanceLog data is stringified and then stored in the transaction log.
=> Add: anonymise-attendance-log job

graphql/subcourse/fields.ts
This simplifies building a UI on top
=> Release course status checks to anyone

common/mails/courses/index.ts, common/mails/templates.ts, common/notification/actions.ts, graphql/subcourse/mutations.ts, notifications/templates.ts
we may have to adjust the templates and the context in `actionTaken`.
In this PR only the logic of suggest courses is implemented, not to promote a course "again".
=> Course suggestions

graphql/authentication.ts, graphql/me/mutation.ts, graphql/student/mutations.ts
See https://github.com/corona-school/project-user/issues/538
=> Prevent students from changing their name by themselves

common/mails/courses/index.ts, graphql/subcourse/mutations.ts
A validation of the course before notify pupil about this course is only necessary when the course gets promoted, not when it gets published!
=> Fix validation promotion of course

common/remission-request/index.ts, common/student/registration.ts, graphql/me/mutation.ts, graphql/student/mutations.ts
https://github.com/corona-school/project-user/issues/495
https://github.com/corona-school/project-user/issues/545
=> Various adaptions to Student registration process

common/transactionlog/types/LogUserEvent.ts, common/transactionlog/types/UpdatePersonalEvent.ts, common/transactionlog/types/UpdatedByScreenerEvent.ts, web/controllers/screeningController/index.ts, web/controllers/userController/index.ts
Closes https://github.com/corona-school/project-user/issues/506
=> Removed personal data from UpdatedByScreenerEvent and UpdatePersonalEvent

common/util/basic.ts, package.json, web/index.ts
in index.ts the only change is in line 376, everything else is formatting
=> start server without resetting db

common/notification/channels/inapp.ts, common/notification/index.ts, common/notification/messages.ts, common/websocket/index.ts, graphql/index.ts, graphql/message_translation/fields.ts
- HOT: Readd hooks, they were lost during merge conflict resolution
- HOT: Disable InApp Channel inside of Jobs Dyno (as no Websocket Server is present)
- Add debug logging for rollout
- Improve Tooling around Message Templates
=> Hotfixes to the notification system

common/websocket/index.ts
- refactored terminating to closing the connection
- added initial websocket CloseCodes based on the rfc
=> refactor: ws server closes connection on error

common/user/index.ts, graphql/student/fields.ts, integration-tests/course.ts
https://github.com/corona-school/project-user/issues/581
=> Reduce instructor findability

common/secret/token.ts
resolves https://github.com/corona-school/project-user/issues/582
=> Email Tokens can be used multiple times for one hour

common/entity/ImportantInformation.ts, common/migration/1677330878850-add-important-notifications.ts, graphql/authorizations.ts, graphql/index.ts, prisma/schema.prisma
Resolves part of corona-school/project-user#609.
Implementation of Important Information entity.
Not completely sure if exposing the Important_informationCrudResolver is desired in graphql/index.ts since no other resolver is implemented that way.
=> Add: configurable ImportantInformation entity

.vscode/settings.json
resolves https://github.com/corona-school/project-user/issues/622
=> Use relative imports in VSCode Autocompletion

common/entity/Pupil.ts, common/entity/PupilScreening.ts, common/migration/1678039222742-pupilscreening.ts, graphql/authorizations.ts, prisma/schema.prisma
Closes https://github.com/corona-school/project-user/issues/623
Closes https://github.com/corona-school/project-user/issues/630
The GraphQL auth rules need revision. I wasn't sure what is desired here, @lsc0498 @Jonasdoubleyou maybe you could clarify?
=> Create pupil screening entity and migration

graphql/course/mutations.ts
needed to create course with category
=> Course categories input for create course

common/notification/actions.ts, common/pupil/screening.ts, graphql/pupil/mutations.ts, graphql/types/enums.ts
closes https://github.com/corona-school/project-user/issues/625
=> create update pupil screening mutation

graphql/index.ts, graphql/pupil_screening/fields.ts
Closes https://github.com/corona-school/project-user/issues/627
=> Add findMany and extended resolver for Pupil_screening

graphql/pupil/mutations.ts, graphql/student/mutations.ts, integration-tests/admin.ts, integration-tests/index.ts, integration-tests/user.ts
https://github.com/corona-school/project-user/issues/649
=> Fix email validation when Admins update the email of users

common/match/create.ts, common/match/request.ts, common/pupil/screening.ts, graphql/pupil/mutations.ts
Closes https://github.com/corona-school/project-user/issues/633
This contains some commits from #512 which should be invisible when #512 has been merged.
see https://github.com/corona-school/project-user/issues/633#issuecomment-1464578745
=> Invalidate screenings of pupil upon matching

common/notification/notification.ts, web/dev.ts
- added new function to replicate message translations
- inspired by `importNotifications`
- tested locally
=> feat: replicate message translations from prod

common/match/pool.ts, common/notification/actions.ts, graphql/match_pool/fields.ts, graphql/match_pool/mutations.ts
Closes https://github.com/corona-school/project-user/issues/629
Closes https://github.com/corona-school/backend/pull/514
=> Pupil screening support for our match pools

common/notification/actions.ts, graphql/pupil/mutations.ts
resolves https://github.com/corona-school/project-user/issues/656
=> Add Notification Action for Pupils joining LF Plus

jobs/periodic/sync-to-webflow/index.ts, jobs/periodic/sync-to-webflow/sync-courses.ts
Some of our courses do not have any image, which breaks the appearance of the webseite. Therefore, we want to set a default image, so that all the items look the same.
Unfortunately, this is not possible in Webflow CMS right now, so we have to do it during the sync job.
https://wishlist.webflow.com/ideas/WEBFLOW-I-1061
=> create default image for webflow course

common/secret/token.ts
Also add some logging and comments
=> Properly override the receiver email on E-Mail Change

integration-tests/course.ts, integration-tests/user.ts, web/dev.ts
And Was not sure about how many courses I should add 😄  @Jonasdoubleyou 
(I think prettify replaced all double quotes " " to single quotes ' ' 👀 )
=> Test for public course suggestions

common/courses/contact.ts, common/courses/lectures.ts, common/courses/states.ts, common/mails/courses/index.ts, graphql/subcourse/fields.ts, graphql/subcourse/mutations.ts
That way we can remove the logic that replicates this in the frontend.
Also move implementations to common for future reuse.
=> Add Decisions canEdit, canCancel, canContactParticipants

common/logger/logger.ts, common/util/bbb.ts, graphql/logging.ts, jobs/periodic/fetch/index.ts, jobs/periodic/fetch/utils/verification/index.ts, jobs/scheduler.ts
This PR will overload the logger.error method, so that we can pass an error as additional data.
=> Refactor error logging

jobs/periodic/sync-to-webflow/sync-courses.ts, jobs/periodic/sync-to-webflow/sync-lectures.ts
This PR is adding the end time of a lecture to the webflow cms collection, which was requested by @tobiasbork .
=> Add webflow fields

.eslintrc, common/courses/participants.ts
Added missing await and raised the eslint-level for required awaits to error
=> Fix check if pupil is already a participant

common/logger/logger.ts, graphql/user/mutations.ts
This PR will send the `userReportIssue` reports to Datadog.
closes https://github.com/corona-school/project-user/issues/688
=> send userReportIssue reports to Datadog

common/student/screening.ts
Closes https://github.com/corona-school/project-user/issues/705
=> Cancel CoC reminders before scheduling new ones

jobs/periodic/sync-to-webflow/sync-courses.ts
This should fix the subject on our lern-fair website. [Example](https://www.lern-fair.de/single-course/1934)
=> translate course subjects before submitting to webflow

graphql/message_translation/fields.ts, utils/helpers.ts
Closes https://github.com/corona-school/project-user/issues/714
=> Fix undefined bug in MessageTranslations

common/match/dissolve.ts
resolves https://github.com/corona-school/project-user/issues/730
=> Fix Match dissolve

common/student/activation.ts, graphql/student/mutations.ts
Closes https://github.com/corona-school/project-user/issues/716
=> Add studentReactivate endpoint

common/appointment/get.ts
- added filter to get also current appointments (start + duration)
=> fix: filter appointments greater than appointment end

common/entity/Match.ts, common/match/dissolve.ts, common/migration/1684167123981-AddMatchDissolvedAt.ts, prisma/schema.prisma
https://github.com/corona-school/project-user/issues/737
=> Add Match.dissolvedAt column

graphql/match/fields.ts
- a pupil should not see appointments, that where declined
=> fix: filter out declined by appointments

graphql/course/mutations.ts, graphql/files.ts, graphql/subcourse/mutations.ts, web/controllers/fileController/index.ts
Resolves backend part of https://github.com/corona-school/project-user/issues/731
I think we could also increase the upload filesize from 5mb to 10mb.
=> feat(file-store): remove tmp-files after successful download and processing

common/logger/logger.ts, common/util/bbb.ts, jobs/periodic/fetch/util.ts
Closes https://github.com/corona-school/project-user/issues/700
=> fix: update all remaining debug logs and swith to message: string

common/chat/conversation.ts, common/chat/helper.ts, common/chat/user.ts, common/entity/Subcourse.ts, common/migration/1685136338879-AddConversationIdToSubcourse.ts, graphql/authorizations.ts, graphql/chat/mutations.ts, prisma/schema.prisma
- instructors are able now to create and contact pupils via the subcourse group chat
=> feat: create subcourse group chat

common/courses/states.ts, common/mails/courses/index.ts, common/notification/index.ts, common/util/basic.ts, graphql/concrete_notification/mutations.ts, graphql/subcourse/mutations.ts
Resolves https://github.com/corona-school/project-user/issues/691
**Open questions:**
1. Where should I put the shuffle function?
Because [shuffling directly on the prisma](https://github.com/prisma/prisma/discussions/5886) query is not possible atm.
2. What should be the predictedPupilResponseRate?
3. What Notification state should be passed when calling bulkCreateConcreteNotifications in bulkactionTaken()?
=> refactor: more resilient course-promotion

graphql/user/mutations.ts, web/server.ts
This PR will move the issue reporter errors to Datadog's [error tracking](https://app.datadoghq.eu/logs/error-tracking?from_ts=1685980314420&to_ts=1685994714420&live=true), so that we don't get notified for the same error again and again.
=> fix(IssueReporter): add issue reporter logs to error tracking

common/entity/InstructorScreening.ts, common/entity/Screening.ts, common/entity/ScreeningTypes.ts, common/migration/1686349982361-add-detailed-screening-data.ts, common/migration/1686439349157-update-screening-types.ts, common/student/screening.ts, graphql/student/mutations.ts, prisma/schema.prisma
Resolves part of https://github.com/corona-school/project-user/issues/750
=> feat(screening-entity): add job status data field

graphql/message_translation/fields.ts
Closes https://github.com/corona-school/project-user/issues/752
=> AllowDeactivated=true in sampleMessage resolver

common/zoom/zoom-user.ts
- added check for `response.ok`
- update user after the check
=> fix: creation sequence for zoom users

common/appointment/create.ts, common/courses/states.ts, common/match/dissolve.ts, common/student/activation.ts, common/user/index.ts, common/zoom/zoom-scheduled-meeting.ts, common/zoom/zoom-user.ts, graphql/appointment/fields.ts, graphql/appointment/mutations.ts, graphql/authorizations.ts, graphql/student/mutations.ts
Allow Admins to create and delete Zoom users and delete Zoom meetings, as well as query them.
=> Zoom Support utilities

common/zoom/zoom-authorization.ts, common/zoom/zoom-scheduled-meeting.ts, common/zoom/zoom-user.ts
- caching only access tokens without a scope
- improved logging
- add trycatch block
=> refactor: improve logs and caching of zoom token

common/appointment/get.ts, graphql/appointment/fields.ts, graphql/appointment/mutations.ts
=> fix: final adjustments to appointments

graphql/appointment/fields.ts, graphql/index.ts
Mainly to check whether all organizers have their zoom user set correctly
=> Add user edges to participants and organizers of appointments

common/notification/notification.ts, graphql/concrete_notification/fields.ts, web/dev.ts
- Properly import from Prod
- Fix notificationCampaigns query
=> Fix Notification Campaing Management

common/appointment/util.ts, common/zoom/zoom-scheduled-meeting.ts, integration-tests/appointments.ts
- added timezone to `toLocaleString` calls
- Removed time zone field and sending iso string to zoom api
=> fix: timezone issues in email and on zoom

graphql/authorizations.ts
- make `matchId` accessable for appointment participants
=> fix: refresh declined or cancelled appointments

jobs/periodic/sync-to-webflow/diff.ts, jobs/periodic/sync-to-webflow/sync-courses.ts, jobs/periodic/sync-to-webflow/sync-lectures.ts
This will make sure that the lectures will always be shown in the right order
=> fix(webflow): order lectures in course

common/courses/participants.ts, common/mails/courses/index.ts
- Free Seats now is free seats (previously was seats taken)
- Decrease estimated response rate to 1% based on first experiences
=> Fix Subcourse Promotion

.env.example, common/slack/blocks.ts, common/slack/format.ts, common/slack/index.ts, jobs/list.ts, jobs/manualExecution.ts, jobs/slack-statistics.ts
resolves https://github.com/corona-school/project-user/issues/814
=> Add Slack Integration

common/match/dissolve.ts
This was brought in with #641 but accidentally reverted with #619
=> Set dissolvedAt when a Match is dissolved

jobs/periodic/redact-inactive-accounts/index.ts
Fixes https://www.notion.so/lern-fair/REDACTED-braucht-eine-Best-tigung-von-dir-394c07f035214e059a3422b867aefc7b
=> fix: remove pending certificate approvals when student is redacted

common/notification/actions.ts, integration-tests/deactivation.ts, integration-tests/redaction.ts, integration-tests/user.ts, jobs/list.ts, jobs/manualExecution.ts, jobs/periodic/redact-inactive-accounts/deactivate-inactive-accounts.ts, jobs/periodic/redact-inactive-accounts/index.ts, jobs/periodic/redact-inactive-accounts/query.ts, jobs/periodic/redact-inactive-accounts/send-inactivity-notification.ts
Fixes https://github.com/corona-school/project-user/issues/570
Here you can find a good [summary](https://lern-fair.slack.com/archives/C01GYCS6DFW/p1690209755201489?thread_ts=1673370004.774589&cid=C01GYCS6DFW)
=> feature: deactivate & annonymize inactive accounts

common/zoom/zoom-scheduled-meeting.ts
https://github.com/corona-school/project-user/issues/831d
=> feat: ignore zoom meeting deletion for 404s 

graphql/rate-limit.ts
Currently Rate Limiting is reported as an error
=> HOTFIX: Make Rate Enforcement Errors well known

common/user/search.ts, graphql/authorizations.ts, graphql/match/fields.ts, graphql/pupil/fields.ts, graphql/pupil/mutations.ts, graphql/student/fields.ts, graphql/student/mutations.ts, graphql/user/fields.ts, integration-tests/screening.ts, seed-db.ts
Add tests for the existing functionality to log in with screener accounts and release user search to screeners.
=> feat: Screener Login

common/notification/index.ts
It's a JSON column, but one large string is written to it which then itself is JSON :/
=> fix: Notification Preferences

common/chat/create.ts, common/chat/types.ts, jobs/periodic/flag-old-conversations/index.ts
=> feat: update meta data of finished conversations

common/logger/logger.ts, common/pupil/screening.ts, common/slack/index.ts, common/websocket/index.ts, jobs/periodic/sync-to-webflow/sync-courses.ts, jobs/periodic/sync-to-webflow/webflow-adapter.ts, utils/helpers.ts
This PR will make sure that all the errors are tracked in Datadog's error tracking.
=> fix: add error object to error logs

jobs/slack-statistics.ts
resolves https://github.com/corona-school/project-user/issues/815
=> feat: Slack Statistics

.env.example, README.md
AWS_REGION=eu is needed as otherwise the backend fails to start
=> doc: Document local setup, adapt .env.example to work out of the box

common/courses/participants.ts
With this the db:seed command works again.
=> fix: Only add Participant to Chat if Chat is active

common/appointment/participants.ts, seed-db.ts
Remove mock Zoom Meetings and fix organizer management on appointments without zoom meeting
=> fix: Zoom seeding

common/appointment/cancel.ts, common/appointment/create.ts, common/appointment/update.ts, common/appointment/util.ts, common/notification/actions.ts
- scheduled appointment reminders 12h before the appointment start 
https://github.com/corona-school/project-user/issues/851
=> feat: appointment reminder

common/student/registration.ts, graphql/authorizations.ts, graphql/cooperation/fields.ts, graphql/cooperation/mutation.ts, graphql/index.ts, graphql/me/mutation.ts, integration-tests/01_user.ts, prisma/migrations/20230911183907_cooperations/migration.sql, prisma/migrations/20230911192341_cooperation_name/migration.sql, prisma/schema.prisma, seed-db.ts
Models Cooperations between Lernfair and some company, whose employees sign up as helpers.
=> feat: Cooperations

graphql/appointment/mutations.ts
(Apparently we don't have a test for it :/)
=> fix: Add missing return to appointmentMatchCreate mutation

graphql/user/fields.ts, integration-tests/02_screening.ts
resolves https://github.com/corona-school/project-user/issues/924
=> feat: Relax usersSearch for screeners

common/notification/actions.ts, common/notification/index.ts, graphql/concrete_notification/mutations.ts, graphql/screener/mutations.ts
https://github.com/corona-school/project-user/issues/929
=> feat: Screeners can send one specific notification to a user

common/chat/retry.ts, common/chat/user.ts
- refers to issue https://github.com/corona-school/project-user/issues/941
=> fix: retry for create a chat user

jobs/index.ts
Error: Error: Looks like you've forgot to provide experimental metadata API polyfill. Please read the installation
=> fix: worker start

graphql/authorizations.ts
Changed permissions so that the email of a pupil can be shown to the screener in the Screening Dashboard.
=> feat: allow screeners to access email

graphql/pupil/mutations.ts
Closes https://github.com/corona-school/project-user/issues/864
=> Add mutation for enabling screeners to update pupil subjects

common/user/roles.ts, graphql/authentication.ts, graphql/roles.ts, graphql/screener/mutations.ts, graphql/secret/mutation.ts, prisma/migrations/20231014132542_add_is_trusted_screener_property/migration.sql, prisma/schema.prisma
Add TRUSTED_SCREENER role which grants privileges to log in with users' accounts
Closes https://github.com/corona-school/project-user/issues/928
=> Add TRUSTED_SCREENER role 

.env.integration-tests, .env.integration-tests.debug, common/chat/conversation.ts, common/chat/user.ts, common/chat/util.ts
- Ensure chat is enabled for every chat functionality
- Log all Chat API calls
- Fix useless existing conversation check
=> feat: Logging & Config Checks for Chat

common/notification/actions.ts, jobs/list.ts, jobs/manualExecution.ts, jobs/periodic/notification-courses-ended-yesterday/index.ts
Add instructor_course_ended and participant_course_ended actions, create job for triggering these actions if a subcourse ended yesterday
Closes https://github.com/corona-school/project-user/issues/963
=> Add instructor_course_ended and participant_course_ended actions

common/courses/participants.ts, common/courses/util.ts, common/mails/courses/index.ts, common/match/request.ts, common/notification/actions.ts
resolves https://github.com/corona-school/project-user/issues/962
resolves https://github.com/corona-school/project-user/issues/961
=> feat: Notifications for Course Full, Match Requests and Join from Waitinglist

common/pupil/activation.ts
resolves https://github.com/corona-school/project-user/issues/995
=> feat: Leave Subcourses when deactivating Pupil

common/match/dissolve.ts, common/notification/actions.ts
resolves https://github.com/corona-school/project-user/issues/973
=> feat: Notification Actions when a Match was dissolved quickly

common/appointment/decline.ts
resolves https://github.com/corona-school/project-user/issues/976
=> feat: Declining the only lecture of a Subcourse leaves the course

graphql/user/mutations.ts
Resolves backend part of https://github.com/corona-school/project-user/issues/1005
=> feat(user): also return user active status on login

common/achievement/aggregator.ts, common/achievement/types.ts
- Closes https://github.com/corona-school/project-user/issues/920
=> feat: achievement standard aggregators

common/student/activation.ts
resolves https://github.com/corona-school/project-user/issues/1021
=> feat: Revoke Certificate Requests on Deactivation

common/achievement/aggregator.ts, common/achievement/create.ts, common/achievement/evaluate.ts, common/achievement/index.ts, common/achievement/metric.ts, common/achievement/types.ts
closes https://github.com/corona-school/project-user/issues/1020
What was done:
1. adjust aggregator functions to unanimous take the buckets for aggregation
2. addition of a count_weeks aggregator function
3. unification of achievementCreation function for all achievement types
4. pass result of evaluation to rewardFunction
5. updating of recordValue if necessary
6.
=> feat: evaluation of streaks

common/chat/conversation.ts
=> fix: Log TalkJS API Error

jobs/execute.ts
Workaround till I find time to implement retry of the transaction
=> fix: Reduce Lock Collisions

common/achievement/aggregator.ts, common/achievement/evaluate.ts, common/achievement/types.ts
Refactoring the aggregators, that they just get values (number[]).
=> feat: refactor of aggregators

common/achievement/get.ts, graphql/types/achievement.ts, graphql/user/mutations.ts
partially closes: https://github.com/corona-school/project-user/issues/1029
What was done:
- mutation to update the isSeen field of user achievements was implemented
=> feat: achievement is seen

common/achievement/get.ts, common/achievement/helper.ts
what was done:
- achievements of streak and tiered get their current values from evaluation in the resolver
=> feat: resolver values

common/achievement/create.ts, common/achievement/get.ts, common/achievement/index.ts, common/achievement/util.ts, common/notification/actions.ts, common/notification/types.ts, graphql/achievement/mutations.ts
what was done:
- issues in the data processing inside the resolver were fixed
=> fix: achievement resolver

common/achievement/create.ts, common/achievement/evaluate.ts, common/achievement/index.ts, common/notification/index.ts
=> feature: add tracing to achievement system

common/notification/actions.ts, graphql/pupil/mutations.ts
Resolves backend part of https://github.com/corona-school/project-user/issues/1008
=> feat: added pupil missed screening mutation

common/student/screening.ts, common/transactionlog/log.ts, graphql/student/mutations.ts, prisma/migrations/20231126170818_add_skipped_coc_log_item/migration.sql, prisma/schema.prisma, seed-db.ts
Closes https://github.com/corona-school/project-user/issues/971
=> feat: add skipCoC parameter when screening an instructor

common/match/pool.ts, graphql/match_pool/fields.ts
resolves https://github.com/corona-school/project-user/issues/840
=> feat: Automatic Invites for Screening

graphql/playground.ts
Pre-fill the admin auth token in dev environments to speed up testing
=> Pre-fill the admin auth token in dev environments to speed up testing

common/chat/deactivation.ts
.milliseconds() returns the milliseconds of the timestamp (usuallly 0 in our case), sorting the lectures by it will do a "random sort" and we pick any lecture of the subcourse instead of the last.
=> HOTFIX: Fix Subcourse Chat Deactivation

common/achievement/aggregator.spec.ts, common/achievement/aggregator.ts, common/achievement/bucket.spec.ts, common/achievement/bucket.ts, common/achievement/evaluate.spec.ts, common/achievement/evaluate.ts, common/achievement/get.ts, common/achievement/index.ts, common/achievement/types.ts, jest/singletons.ts, jobs/index.ts, package-lock.json, package.json, types/custom.d.ts, web/index.ts
First set of unit tests that are covering achievement evaluation as well as aggregators and bucket creators.
=> Create evaluate unit tests

graphql/match/fields.ts
resolves https://github.com/corona-school/project-user/issues/951
=> feat: Stop sharing EMail with Match Partner

.github/workflows/node.js.yml, common/achievement/bucket.spec.ts, common/achievement/evaluate.spec.ts, package.json
=> fix: unit tests should work in ci

common/achievement/bucket.spec.ts, common/achievement/bucket.ts, common/achievement/create.ts, common/achievement/evaluate.spec.ts, common/achievement/evaluate.ts, common/achievement/get.ts, common/achievement/index.ts, common/achievement/metric.ts, common/achievement/metrics.ts, common/achievement/template.ts, common/achievement/types.ts, common/achievement/util.ts, common/logger/logger.ts, graphql/types/achievement.ts
I manually set "strict": true in tsconfig and fixed all achievement related issues.
=> fix: typesystem for achievements

common/util/subjectsutils.ts, prisma/migrations/20240115164201_add_lernen_lernen/migration.sql, prisma/schema.prisma
Closes https://github.com/corona-school/project-user/issues/946
=> Add subject "Lernen lernen" to enums

common/zoom/user.ts
https://github.com/corona-school/project-user/issues/1128
=> fix: Proper error message for Zoom user deletion & Ignore if user doesn't exist

common/secret/token.ts, common/user/index.ts, common/user/update.ts, common/zoom/user.ts, graphql/appointment/fields.ts
- Closes https://github.com/corona-school/project-user/issues/1118
- Closes https://github.com/corona-school/project-user/issues/1116
=> feat: get zoom url

common/pupil/screening.ts, graphql/pupil/mutations.ts
I.e. when creating a first screening during registration
https://github.com/corona-school/project-user/issues/740
=> feat: Add pupil screening without inviting pupils

graphql/types/achievement.ts
Already bring in GraphQL changes from https://github.com/corona-school/backend/pull/950 to avoid conflicts in frontend
=> ci: Fast track GraphQL changes

common/user/session.ts
As Keyv serializes entries, we need to explicitly set
=> fix: Session Update

graphql/user/fields.ts
That way we can build proper Retool debugging tools.
Also fix the other achievement field resolvers using the context instead of the root
https://github.com/corona-school/project-user/issues/1120
=> feat: Expose internal achievement data via GraphQL

common/achievement/bucket.spec.ts, common/achievement/bucket.ts, common/achievement/index.ts, common/appointment/tracking.ts, common/notification/actions.ts
- closes https://github.com/corona-school/project-user/issues/1147
- refactoring of bucket creation für lecture related buckets
- additional context for meeting join actions
- lecture start as date for joined meeting events
=> feat: assign lecture start to event creation time

common/achievement/create.ts, common/achievement/get.ts, common/achievement/util.ts, seed-db.ts
- closes https://github.com/corona-school/project-user/issues/1147
- added relations to achievementsByGroup-Key
=> fix: group achievement relation streak global

common/achievement/evaluate.ts, common/achievement/util.ts
- time frame filters were removed from getBucketContext function
- filter function was introduced to pull out buckets for future lectures not containing elements
=> fix: adjust bucket filter

jobs/slack-statistics.ts
Only show verified pupil/student registrations in slack statistics
=> Only show verified pupil/student registrations in slack statistics

common/achievement/create.ts, common/achievement/get.ts, common/achievement/index.ts, common/achievement/template.spec.ts, common/achievement/template.ts, graphql/achievement_template/mutations.ts, prisma/migrations/20240217201951_add_achieved_description_field_to_achievement_template/migration.sql, prisma/schema.prisma, seed-db.ts
This PR is adding a new achievedDescription field to replace the sequential achievement hack.
Solves
https://github.com/corona-school/project-user/issues/1109
=> feature: remove sequential achievement hack

common/achievement/create.ts, common/achievement/index.ts, common/logger/metrics.ts
This can be used for visualisation and alerting later on.
No user data is included
=> feature: add some achievement related DD metrics

common/achievement/get.ts
This will fix the important notifications.
=> fix: next step achievements for important notifications

common/appointment/cancel.ts
Trigger appointment cancellation actions also for course appointments, if a course is cancelled.
=> fix: Cancel reminders when cancelling courses

common/achievement/get.ts
This PR prevents something like this
Streaks have to be generated in advance for evaluation. Unfotunately, this doesn't automatically mean that we'll reach a first record.
Therefore, we hide streaks that never had a record yet.
=> fix: filter never achieved streaks

graphql/authorizations.ts
https://github.com/corona-school/project-user/issues/1173
Follow up PR of https://github.com/corona-school/user-app/pull/515
=> feat: Grant screeners access to pupils verifiedAt

common/notification/index.ts
https://github.com/corona-school/project-user/issues/1170
I moved the logic that prevents sending emails to unverified users to be after we cancel reminders.
I tested it with the case we discussed _(CoC for unverified user after 30 days)_
The only thing I'm thinking now is that all the logs from the `Determine which Notifications to send directly and which to schedule` section will still be executed which is a bit weird
=> fix: Move unverified users check to after cancelling reminders

common/courses/notifications.ts, graphql/user/fields.ts
include pupils that had a match or were in a subcourse at some point
=> Course Promotions/Campaigns: include more pupils

common/appointment/get.ts, graphql/match/fields.ts
https://github.com/corona-school/project-user/issues/1177
- Updated the existing match `appointments` resolver to accept pagination parameters
- Added utility functions for pagination
[Frontend PR](https://github.com/corona-school/user-app/pull/519)
=> Feature: Pagination for match appointments

common/notification/channels/mailjet.ts, integration-tests/12_notifications.ts
Fix: prevent generation of new login token when changing email (email change mutation already generates a new token)
=> Fix: prevent generation of new login token when changing email

common/pupil/screening.ts, graphql/pupil/mutations.ts, prisma/migrations/20240423134900_add_knows_corona_school_from_to_pupil_screening/migration.sql, prisma/schema.prisma
https://github.com/corona-school/project-user/issues/1179
- Added `knowsCoronaSchoolFrom` field to pupil screenings, similar to how we have it on the other models
=> Feature: Add knows from field for sus screenings

common/chat/deactivation.ts, graphql/subcourse/mutations.ts
resolves https://github.com/corona-school/project-user/issues/1182
=> feat: Keep canceled subcourse chats open for 30 days

common/user/evaluate_roles.ts, common/user/roles.ts, graphql/authorizations.ts, graphql/course/fields.ts, graphql/course/mutations.ts, graphql/pupil/fields.ts, graphql/pupil/mutations.ts, graphql/screener/mutations.ts, graphql/student/fields.ts, graphql/student/mutations.ts, graphql/subcourse/fields.ts, graphql/subcourse/mutations.ts, graphql/user/fields.ts, integration-tests/02_screening.ts, prisma/migrations/20240425184739_add_screener_roles/migration.sql, prisma/schema.prisma, seed-db.ts
Introduces screener roles that can be granted by admins.
=> feat: Screener roles

common/appointment/create.ts, graphql/match/mutations.ts
https://github.com/corona-school/project-user/issues/1193
- Included the `zoomUrl` in the response of the `matchCreateAdHocMeeting` response
Frontend PR [here](https://github.com/corona-school/user-app/pull/527)
=> feat: Add zoom url for adhoc meetings

common/match/util.ts, graphql/pupil/fields.ts, graphql/subcourse/fields.ts
https://github.com/corona-school/project-user/issues/1194
- Exposed the `gradeAsInt` property for Instructors and Tutors
- Updated the defaultTutoringGradeRestrictions to support grade 14
[Frontend PR here](https://github.com/corona-school/user-app/pull/529)
=> feat: Expose gradeAsInt for tutors/instructors

common/student/screening.ts, graphql/student/mutations.ts
https://github.com/corona-school/project-user/issues/1195
Added two mutations to update instructor / tutor screenings
=> feat: Add mutations to update student screenings

common/notification/channels/push.ts, common/pupil/activation.ts, common/student/activation.ts, graphql/authorizations.ts, graphql/user/fields.ts, graphql/user/mutations.ts, prisma/migrations/20240509190036_add_push_subscription/migration.sql, prisma/migrations/20240509195123_make_subscription_expiration_optional/migration.sql, prisma/schema.prisma
Users can add, get and remove push subscriptions. 
https://github.com/corona-school/project-user/issues/606
=> feat: Web Push / Manage Subscriptions

common/notification/defaultPreferences.ts
https://github.com/corona-school/project-user/issues/1210
Update default preferences when the newsletter is disabled
[Frontend PR here](https://github.com/corona-school/user-app/pull/537)
=> feat: Adjust preferences when newsletter is disabled

graphql/subcourse/fields.ts
Fixing filter combination of courseState and subcourseSearch to be AND instead of OR
=> fix courseState & subcourseSearch filter combination

common/notification/channels/push.ts
Setting it to "false" should turn it off ...
=> fix: Push config toggle

common/notification/index.ts, graphql/user/fields.ts
https://github.com/corona-school/project-user/issues/1236
- Merge stored with default preferences on field resolver, to display the actual preferences state in the UI correctly
=> fix: Merge user preferences with default preferences

jobs/periodic/redact-inactive-accounts/query.ts
Closes https://github.com/corona-school/project-user/issues/1022
=> Fix: exclude default screener from account redaction

common/notification/channels/push.ts
https://github.com/corona-school/project-user/issues/1258
- Catch errors from`webPush.sendNotification`
- Remove invalid/expired subscriptions
Tested it locally and expired subscriptions are correctly removed 🚀
@Jonasdoubleyou I'll merge to test it with Fredrik on STG :) Let me know if there is something we could improve here.
=> fix: Catch WebPush errors and remove invalid subscriptions

common/notification/channels/push.ts
https://github.com/corona-school/backend/pull/1107#discussion_r1658538790
=> Fix: Add missing logs

common/util/subjectsutils.ts, prisma/migrations/20240629092815_issue1043/migration.sql, prisma/schema.prisma
Added 'Arbeitslehre', 'Ethik', 'Gesundheit' and 'Technik' as new subjects to subjectsutils.ts and schema.prisma. Also generated the corresponding migration file
Resolves corona-school/project-user#1043
=> feat: added 4 new subjects to subjectsutils.tx and schema.prisma

common/notification/index.ts, integration-tests/12_notifications.ts, prisma/migrations/20240702073053_add_disabled_channels/migration.sql, prisma/schema.prisma
https://github.com/corona-school/project-user/issues/1263
- Added a new field `disabledNotifications` on the `notification` model
- Added validation to check for disabledChannels
=> Feat: Add disabled channels for notifications

graphql/authorizations.ts, graphql/user/fields.ts, prisma/migrations/20240704092945_add_concrete_notification_relation/migration.sql, prisma/schema.prisma
https://github.com/corona-school/project-user/issues/1267
- Added notification - concrete_notification relationship 
- Added filters to skip non-relevant notifications for the user app
=> Fix: Filter out non relevant notifications

common/notification/actions.ts, common/util/gradestrings.ts, graphql/authorizations.ts, graphql/pupil/mutations.ts, prisma/migrations/20240709130015_add_grade_updated_at_field/migration.sql, prisma/schema.prisma
https://github.com/corona-school/project-user/issues/574
- Add mutation `adminIncreasePupilGrades`
- Execute action when increasing pupil grade via this mutation
=> Feat: Increase pupils grade mutation

common/match/dissolve.ts, common/notification/actions.ts
https://github.com/corona-school/project-user/issues/1296
- Added actions when a match is dissolved after 30 days
=> feat: Add actions when a match is dissolved after 30 days

seed-db.ts
https://github.com/corona-school/backend/issues/1154
Improve the data we have available on STG by adding more realistic information. _(For demos or just testing purposes)_
- Added some utility functions to avoid code duplication while creating test data
- Added more test courses
- Added more test appointments
- Added more test instructors
- Added more test matches
- Removed deprecated test-data
=> chore: Improve test data

graphql/student/mutations.ts
https://github.com/corona-school/project-user/issues/1297
- Allow student screeners to update students
=> feat: Allow student screeners to update students

graphql/subcourse/fields.ts
This allows us to jump to the prospect chat from the prospect list.
Related PR: https://github.com/corona-school/user-app/pull/560
=> Feat: expose prospect chat's conversationId when calling prospectParticipants resolver

graphql/pupil/fields.ts, graphql/pupil/mutations.ts, graphql/student/mutations.ts
- Allow read/update of pupil's `school` field
=> feat: Allow screeners to update pupil school

graphql/pupil/fields.ts, graphql/student/mutations.ts
- Removed wrong validation for EthicsOnboarding
- Added validation when fetching pupils that don't have schools
=> Fix: Validations

seed-db.ts
- Add default ethicsOnboarding completed
- Add missing course tags
=> chore: Test data improvements

common/match/matching.spec.ts, common/match/matching.ts
If pupils request to be matched with a certain gender this is a constraint in the matching algorithm
https://github.com/corona-school/project-user/issues/1383
=> feat: Gender Match Constraint

common/match/matching.spec.ts, common/match/matching.ts
Only match offers that have special experience with requests that have special needs.
https://github.com/corona-school/project-user/issues/1383
=> feat: Match Constraint Special Needs/Experience

graphql/course/mutations.ts, prisma/migrations/20250102184945_add_homework_help_course_category/migration.sql, prisma/schema.prisma
Add homework help course category and make it impossible for non-authorized users to create such courses
=> Feat: Add homework help course category

common/achievement/evaluate.spec.ts, common/match/dissolve.ts, graphql/match/mutations.ts, prisma/migrations/20250120153017_add_otherdissolvereason_string/migration.sql, prisma/schema.prisma
Add column for detailed free text other dissolve reason
Closes https://github.com/corona-school/project-user/issues/1403
=> Feat: add column for detailed free text other dissolve reason

common/secret/idp.ts, common/user/evaluate_roles.ts, common/user/roles.ts, graphql/authentication.ts
Part of https://github.com/corona-school/project-user/issues/1429
- Added a `SSO_USER` Role. Will be used to change the app behavior for these users _(Hide some functionalities / adjust how it works)_
=> feat: add SSO_USER Role

README.md, common/achievement/Readme.md
This PR is adding a new README containing information about our achievement system.
It's not complete yet, but includes a lot of useful information. I'll add missing topics in follow-up PRs.
=> feature: create achievement docs

graphql/statistics/fields.ts
Closes https://github.com/corona-school/project-user/issues/1430
=> Feat: add query for getting deactivation reason stats

common/appointment/create.ts, common/appointment/util.ts, common/notification/types.ts, graphql/appointment/fields.ts, graphql/course/mutations.ts, package-lock.json, package.json
Closes https://github.com/corona-school/project-user/issues/1462.
- Introduce function for generating ICS file for group appointments and match appointments, for both instructors and participants
- Send out ICS files as notification attachments, in both initial appointment creation emails (participants only) and reminder emails sent 12 hours before appointment start (both instructors and participants)
```
title: displayName,
description: appointment.description ?? undefined,
url: `https://app.lern-fair.de/appointment/${appointment.id}`,
location: `https://app.lern-fair.de/appointment/${appointment.id}`,
alarms: [
{
action: 'display',
trigger: { hours: 1, minutes: 0, before: true },
description: `Erinnerung: ${displayName}`,
},
],
busyStatus: 'BUSY',
transp: 'OPAQUE',
```
Some notes: 
- We …
=> Feat: send ICS calendar files as attachments

common/courses/notifications.ts, common/courses/util.ts, common/notification/actions.ts
- Added grade range in the subcourse context to be used in email templates
=> feat: Add subcourse grade range in subcourse context

graphql/subcourse/fields.ts, graphql/subcourse/mutations.ts, seed-db.ts
Resolves https://github.com/corona-school/project-user/issues/1481
- Allow non-instructor students to see and join the Hausaufgabenhilfe course
- Fix log
- Update Hausaufgabenhilfe course on STG to match the production state
=> Feat: Allow non-instructor students to see and join the Hausaufgabenhilfe course

common/appointment/create.ts, common/appointment/decline.ts, common/appointment/participants.ts, common/appointment/update.ts, common/courses/participants.ts, common/courses/states.ts, common/courses/util.ts, graphql/appointment/mutations.ts, graphql/course/mutations.ts, jobs/periodic/notification-courses-ended-yesterday/index.ts
Resolves https://github.com/corona-school/project-user/issues/1480
- Turned off appointment notifications for the Homeworkhelp course
=> Feat: Do not send notifications for Homeworkhelp course

common/notification/hooks.ts
Related to https://github.com/corona-school/project-user/issues/1477
=> fix: Remove invalidation of screenings when revoking pupil match request

common/util/subjectsutils.ts, prisma/migrations/20250611132825_add_steuerlehre_subject/migration.sql, prisma/schema.prisma
Resolves https://github.com/corona-school/project-user/issues/1496
Added a new subject `Steuerlehre`
=> feat: add new subject - Steuerlehre

graphql/authorizations.ts
- Make calendarPreferences public to be accessible for matches
=> feat: Make calendarPreferences public

common/match/request.ts
Resolves https://github.com/corona-school/project-user/issues/1509
Added check to exclude first screening from invalidation after requesting a match
=> fix: Exclude first screening from invalidation when requesting a match

common/notification/actions.ts, common/pupil/screening.ts
Resolves https://github.com/corona-school/project-user/issues/1531
=> feat: Add action for pupils rejection while having an active match
