common/mails/config.ts
common/mails/templates.ts

This pull request will add the required **templates** for mails that were sent in context of Corona School's courses: 
* notify participants that a course was cancelled
* remind an instructor of an upcoming course
* remind a participant of an upcoming course

Add mail templates for courses

---

.github/workflows/node.js.yml

This moves the linter to its own job in the actions yml, so it's not executed for all node versions but only for the single specified one (reducing the amount of duplicated warnings in PRs)

Run linter only once

---

jobs/periodic/feedback-request/index.ts

adds an await to wait for the mail to be sent before saving having the mail sent. This was mentioned by @geroembser in #92. Otherwise matches will have information of mails having been sent, that have not been, if the sending had an error

fix sending of feedback requests

---

common/entity/ProjectMatch.ts
common/entity/Pupil.ts
common/entity/Student.ts
common/mails/templates.ts
common/migration/1605738493568-JufoUserAPI.ts
common/transactionlog/types/LogType.ts
common/transactionlog/types/ProjectMatchDissolveEvent.ts
common/transactionlog/types/UpdateProjectFieldsEvent.ts
web/controllers/projectMatchController/format.ts
web/controllers/projectMatchController/index.ts
web/controllers/userController/format.ts
web/controllers/userController/index.ts
web/dev.ts
web/index.ts

This will add several API endpoints for users that are intended to enable the project coaching part of our user section.
This includes: 
What still needs to be done.

Project Coaching User API endpoints

---

assets/certificateTemplate.html
assets/verifiedCertificatePage.html
web/controllers/certificateController/index.ts
web/index.ts

As we start working on the frontend tomorrow, I'd like to deploy this to dev today. 
The added API /api/certificates exposes all certificates the user is involved in (either as a student or pupil).

API for user certificates & Cleanup

---

web/controllers/courseController/format.ts
web/controllers/courseController/index.ts

This might have been a performance issue leading to loading times of up to 5s in production.

Don't send corresponding courses with tag when querying GET /courses/tags

---

web/controllers/screeningController/index.ts

As far as I can see, the instructor review page for which this search was originally built was replaced with something else.
This API endpoint is now only used for the "Manage Instructors" dialogue.
In that dialogue, it seems as if one can search instructors by full name, however that is not quite true, as the current implementation searches by lastname only.
So I thought to finish up the "search in review" topic, I'll align the behavior of this search with the one in the courses search, allowing users to search by fullname.

Improve instructor search by firstname

---

common/prisma/index.ts
package-lock.json
package.json
web/controllers/screeningController/index.ts
web/index.ts

From the logs this seems to return reasonable queries, so the performance issues should be gone. I'm fairly confident that the behavior did not change. 
Had to upgrade Prisma to perform all the filtering on the database, according to the [changelog](https://github.com/prisma/prisma/releases) none of the breaking changes should affect us. For some reason the newest 2.17 produces invalid Typescript types, so I went for 2.16.2 instead.

Rewrite Screening Queries to Prisma to eventually fix the performance problems

---

common/dto/StudentEditableInfoDTO.ts
common/dto/StudentInfoDTO.ts
web/controllers/tokenController/index.ts

This adds a check to the login procedure which checks if the user is verified. If they aren't yet, a new verification email will be sent to [enforce e-mail verification](https://github.com/corona-school/project-user/issues/267)

Added login check to see if user is verified

---

common/dto/StudentEditableInfoDTO.ts
common/dto/StudentInfoDTO.ts

Now passing the verification string to the screening backend, as this is a more reliable way of telling if a student has a verified email address.

replaced verifiedAt with verification in StudentInfoDTO

---

web/controllers/courseController/index.ts

I recognize that this should be part of an easily modifiable config at some point, but I figured that it would be better to change the (hardcoded) constant right away because of the urgency of the issue.
Closes https://github.com/corona-school/project-user/issues/339

Raised course limit to 10

---

.env.example
app.json
common/courses/certificates.ts
common/prisma/index.ts
package-lock.json
package.json
web/controllers/certificateController/index.ts
web/controllers/notificationController/index.ts
web/index.ts

This way NODE_ENV can be set to production by default (which causes Heroku to drop dev dependencies during build, reducing the slug size to about 400MB, which is 100MB away from the hard limit which we currently run into)

Move config variable from NODE_ENV to ENV

---

common/transactionlog/types/DeActivateEvent.ts
web/controllers/userController/index.ts

With this change, the frontend can provide a deactivation reason as well as additional feedback when the user decides to deactivate their account.
The additional information then gets written to the transaction log as part of the DeActivateEvent.
See https://github.com/corona-school/project-user/issues/302 for more details.

Allow deactivation reason and feedback

---

web/controllers/userController/index.ts

During the user settings update modal, the whole user account gets posted to the PUT /api/user endpoint. 
If an Admin manually matched a pupil, the endpoint will reject the user, and as such the Modal will end with an error. 
See https://app.logdna.com/3cfa259833/logs/view?t=timestamp%3A1630659184908&a=1630659184908.1386885141898444803&q=%229fee9e5a-55e3-485d-bab7-981a4ff13021%22 for a concrete occurence. 
To resolve this, the logic was adapted to only prevent users from increasing the match count. 
This should resolve https://github.com/corona-school/project-user/issues/384

HOTFIX: Fix match request validation to resolve issues with Modal

---

common/notification/notification.ts
graphql/notification/mutations.ts
package-lock.json
package.json
prisma/schema.prisma
web/dev.ts

Apart from improved logging, this provides means to import notifications into a system. Through that we can easily replicate the Notification configuration from QA and PROD and  vice versa. Through a "dry run", we can check whether the configuration can be applied and what it does. This way we can add such functionality to Retool and let content admins manage those (less work for the Tech Team). 
In theory we could also replicate the PROD configuration every time the QA environment is rebuilt

Add notification import and update, improve logging

---

graphql/index.ts
graphql/pupil/fields.ts
graphql/tutoring_interest_confirmation/mutations.ts

Adds the following subquery to pupils:
```gql
query {
pupils {
tutoringInterestConfirmation {
status 
token
reminderSentDate
}
}
}
```
Also adds two mutations to confirm or deny the interest:
```gql
mutation { tutoringInterestConfirm(token: "abc") }
mutation { tutoringInterestRefuse(token: "abc") }
```

Mutations and Resolvers for Interest Confirmation

---

common/certificate/index.ts
graphql/authorizations.ts
graphql/certificate/fields.ts
graphql/certificate/mutations.ts
graphql/index.ts
graphql/pupil/fields.ts
graphql/student/fields.ts
web/controllers/certificateController/index.ts

resolves https://github.com/corona-school/project-user/issues/373
Pupils can run this query:
```gql
query { 
me {  
pupil { 
participationCertificatesToSign { 
id
uuid
subjects
categories
certificateDate
startDate
endDate
hoursPerWeek
hoursTotal
medium
ongoingLessons
state
signatureLocation
}
}
}
}
```
Students can get the same through:
```gql
query { me { student { participationCertificates { ... } } }
```
Also adds three mutations:
```gql
mutation { 
participationCertificateAsPDF(language: "de" uuid: "B2FEB67654")
}
```
```gql
mutation { 
participationCertificateCreate(pupilId: 1 certificateData: { 
endDate: 200000 
subjects: "Deutsch,Englisch" 
hoursPerWeek: 5 
hoursTotal: 10 
medium: "PC" 
activities: "test"  
ongoingLessons: true 
state: "awaiting-approval"
}
}
```
```gql
mutation { …
```

GraphQL: Participation Certificates

---

.eslintrc
web/controllers/certificateController/index.ts

```
curl https://backend-hotfix-certific-sokjbo.herokuapp.com/api/certificates -H "token: authtokenP1"
```
now properly returns the certificates instead of an empty object. 
The bug has not yet arrived in PROD though but is currently only in DEV.

HOTFIX: Fix /api/certificates endpoint

---

graphql/authorizations.ts
graphql/match/fields.ts
graphql/pupil/fields.ts
graphql/student/fields.ts
graphql/types/subject.ts

Pupils can see the public data of their matched students and vice versa. 
```gql
query { 
me { 
pupil { 
matches { 
id 
pupil { 
id
authToken # as this is a self reference, the pupil can also see all their data here
}
student { 
id
firstname
lastname
languages
subjectsFormatted { name grade { min max }}
}
}
}
}
}
```

GraphQL: Release Student / Pupil entities via match association

---

README.md
common/util/basic.ts
package.json
web/index.ts

Closes https://github.com/corona-school/project-user/issues/398
This adds support for the `--noPDF` command line argument and adds a new npm script that runs the project in dev mode, but with this new argument: `npm run web:nopdf`

Add flag to disable browser initialization and puppeteer

---

web/dev.ts

This can happen if an Admin added a match manually, and as such should be tested

Tests: Add second match to pupil

---

jobs/list.ts

That way reminders are easier to test, hourly reminders actually work as scheduled and the workload is distributed over the day (though that shouldn't matter anyways).

Send out reminders hourly

---

common/administration/match-making/tutoring/matches/notify/mail.ts
common/match/create.ts
common/match/dissolve.ts
common/notification/ACTIONS.md
web/controllers/matchController/index.ts

Large numbers seem to crash Mailjet's API internally, c.f. https://twitter.com/mailjet/status/1270003900528066567 (great that this is only documented on Twitter ...)

Fix Mailjet Crash - Pass matchDate as string

---

common/notification/bulk.ts
web/controllers/userController/index.ts

The `dissolveMatch` function reads the user record from the DB, thus the account deactivation must be persisted before dissolving all matches.

Fix: Persist deactivation before sending out match dissolve mails

---

common/match/pool.ts
graphql/match_pool/fields.ts
integration-tests/matching.ts

```gql
query { 
match_pool(name: "lern-fair-now") { 
statistics { 
matchesByMonth
averageMatchesPerMonth
predictedPupilMatchTime
subjectDemand { subject demand }
}
}
}
```
can be executed unauthenticated on [branch deployment](https://backend-feat-matching-s-vv56wt.herokuapp.com/apollo)
I guess we need a few iterations till the predictions are actually accurate

Matching Statistics

---

common/entity/ExpertData.ts
common/file-bucket/delete.ts
common/file-bucket/put.ts
common/file-bucket/s3.ts
common/mails/config.ts
common/mails/index.ts
common/mails/mailjet.ts
common/mails/mailjetTypes.ts
common/notification/channels/mailjet.ts
common/util/basic.ts
common/util/bbb.ts
package-lock.json
package.json
web/controllers/courseController/index.ts
web/controllers/expertController/index.ts

This PR aims to clean up a few dependencies listed in https://github.com/corona-school/project-user/issues/449.
* Bumped node version to 18.x to support native `fetch`
* Implemented custom mailjet solution to avoid having to ship the SDK
* Migrated the S3 SDK to v3 which is modular, resulting in a smaller dependency size

Reduce Dependencies

---

.eslintrc
graphql/mentor/mutations.ts
graphql/statistics/fields.ts
graphql/subcourse/mutations.ts
linter/graphql-undeferred-impossible.js
linter/index.js
package-lock.json
package.json

As the Linter was not working correctly, various missing authorizations went unnoticed (fortunately only statistics, so no sensitive data was exposed). Additionally the linter did not check whether `@Authorized` was used incorrectly on a mutation with root-dependent roles (which is nonsense as there is no Root entity on a Mutation). This is now correctly validated and all wrong authorization checks are adapted.

Fix Authorizations

---

common/attachments/index.ts
common/courses/contact.ts
common/notification/index.ts
graphql/certificate/mutations.ts
graphql/course/mutations.ts
graphql/files.ts
graphql/student/fields.ts
graphql/subcourse/fields.ts
graphql/subcourse/mutations.ts
graphql/types/instructor.ts

(1) Instructors can find other instructors:
```gql
query { 
otherInstructors(take: 10 skip: 0 search: "") { 
id
firstname
lastname
}
}
```
(2) Instructors can add / remove other instructors:
```gql
mutation { 
courseAddInstructor(studentId: 2 courseId: 3)
}
mutation { 
courseDeleteInstructor(studentId: 2 courseId: 3)
}
mutation { 
subcourseAddInstructor(studentId: 2 subcourseId: 11)
}
mutation { 
subcourseDeleteInstructor(studentId: 2 subcourseId: 11)
}
```
(3) Instructors can contact participants:
```gql
mutation { 
subcourseNotifyParticipants(subcourseId: 11 title: "Test" body: "Test" fileIDs: [] participantIDs: [1])
}
```
(4) Participants can contact instructors, if allowed:
```gql
query { 
me { 
pupil { 
subcoursesJoined { 
canContactInstructor { allowed reason }
}
}
}
}
mutation { …
```

Subcourse messaging, find further instructors, manage instructors

---

common/pupil/registration.ts
common/secret/token.ts
common/student/registration.ts
graphql/me/mutation.ts

- `noEmail: true` can be passed to `meRegisterPupil` and `meRegisterStudent`, decoupling the email verification from the registration
- Using an email token for authentication verifies the email
- New tokenRequest type user-registration used during the registration flow to verify the email

Adaptions to Registration E-Mail Process

---

graphql/concrete_notification/dummy_data.ts
graphql/concrete_notification/fields.ts
graphql/index.ts
graphql/notification/fields.ts
graphql/ownership.ts
graphql/user/fields.ts

adds a new resolver for user's (concrete) notifications
for testing locally run "npm run build" first, than you can try new query in graphql playground at http://localhost:5000/apollo
an example query would be 
```
#mutation{loginLegacy(authToken: "authtokenP1")} #uncomment and run this line first for auth
{me{concreteNotifications{id,headline,body,createdAt,notification{messageType}}}}
```

 #LF-6 add dummy notifications resolver

---

common/courses/participants.ts
common/transactionlog/types/CreateCourseAttendanceLogEvent.ts
graphql/subcourse/mutations.ts

This is necessary for https://github.com/corona-school/project-user/issues/499. This is just the normal subcourseJoin endpoint but it bypasses the `canJoinSubcourse` function, course capacity check and `pupilSubCourseCount > PUPIL_MAX_SUBCOURSES` check

Add subcourseJoinManual endpoint

---

graphql/authentication.ts
graphql/context.ts
graphql/user/fields.ts
package-lock.json
package.json
web/index.ts

Session Token can now be placed in a cookie via `mutation { createCookieSession }` and the session token is then read from the cookie (as an alternative to the Bearer authorization header). As passing Cookies is well supported in various tools (including Retool) this simplifies porting GraphQL access to these platforms.

Retool Login to Backend

---

common/notification/hooks.ts
common/notification/index.ts
common/student/activation.ts
jobs/index.ts
jobs/manualExecution.ts

Inside the Jobs Dyno, the student-deactivate hook was not registered and could thus not be executed by the Notification System when running inside Jobs. By making hooks a direct dependency of the Notification System this should work now.
Also provide a possibility to test this, by running jobs manually.

Fix CoC Deactivation inside Jobs Dyno

---

graphql/authorizations.ts

Urgent, as:
- Users can currently bypass email verification
- Users might access sensitive data of other accounts (i.e. their match partners, course tutors, ...)
Affected since Monday night, so probably not abused yet.

HOTFIX: Prevent access to ConcreteNotification context via GraphQL

---

common/pupil/registration.ts
graphql/me/mutation.ts
integration-tests/matching.ts
integration-tests/user.ts

1. Pupils get automatically the role `pupil` and `participant` when they register. 
2. Extend Integration tests with that.
3. Add `becomeParticipant` endpoint

Pupil registration fix (#471)

---

common/certificate/index.ts
graphql/certificate/mutations.ts
web/controllers/certificateController/index.ts

The old API uses UNIX timestamps in seconds, and improperly validates it. Let's just use GraphQL's Date Type instead for the GraphQL based API

Allow overriding the startDate of certificates, fix time handling

---

README.md
package.json
web/index.ts

Raises the default log level to INFO, debug logging can be enabled with the `--debug` flag.
The logging in the GraphQL stack is generally more verbose (which is a good thing in case one needs to debug something), but by default we should switch it off as we log tons of data otherwise that no one can work with anyways (and Mezmo complains about our log volumes)

Increase log level

---

common/courses/participants.ts
graphql/subcourse/fields.ts
graphql/subcourse/mutations.ts

- Instructors can query the pupils on the waitinglist:
```gql
query { subcourse(...) { pupilsOnWaitinglist { id firstname lastname } } }
```
- Pupils can check whether they can join the waitinglist:
```gql
query { subcourse(...) { canJoinWaitinglist } } }
```
- Instructors can join single pupils from the waitinglist:
```gql
mutation { subcourseJoinFromWaitinglist(subcourseId: 1, pupilId: 1) }
```

Allow instructors to manage the waiting list

---

common/entity/PupilScreening.ts
common/migration/1678045632307-default-pupil-screening.ts
common/notification/actions.ts
common/pupil/screening.ts
graphql/authorizations.ts
graphql/pupil/fields.ts
graphql/pupil/mutations.ts
prisma/schema.prisma

Closes https://github.com/corona-school/project-user/issues/624
> Inform stakeholders about actionId such that they can create the appropriate email template
@lsc0498 @Maascha The action ID for creating a pupil screening is `pupil_screening_add`.

GraphQL mutation for creating pupil screenings

---

web/index.ts
web/setupLogger.ts

I noticed the logger was not working during the pupil screening update mutation PR.
The problem is that log4js needs to be configured before running `getLogger`, because otherwise, a new logger with `level: 'OFF'` is created.
This PR will ensure that the first thing in the web/index is setting up the logger so we can use `getLogger` in the root of all the following imports.
We should refactor the usage in the future to have a similar setup to the job/index.

fix web logger

---

graphql/authorizations.ts

It can definetly happen that non pupils access the resolver guarded by the authorization, in that case we just want to continue and throw a regular authentication error instead of an INTERNAL SERVER ERROR.
(This was only hit by a user once so far, as you need to directly perform some action on the subcourse without running _any other query before_ that would trigger reauthentication).

Remove assertion in SUBCOURSE_PARTICIPANT check

---

graphql/notification/fields.ts

Changed authentication of messageTranslations to `Role.UNAUTHENTICATED` to be able to import them in dev environments

refactor: open message translations

---

common/websocket/index.ts

- implemented heartbeat by pinging all client connections
- added debug logs
```log
[2023-03-24T14:05:53.707] [DEBUG] Websockets - Pinging client with ConnectionId(37bdd08f-fbc4-4618-9b42-d6689833d7fd) of User UserId(student/1)}
[2023-03-24T14:05:53.712] [DEBUG] Websockets - Received pong from ConnectionId(37bdd08f-fbc4-4618-9b42-d6689833d7fd) of user UserId(student/1)}
[2023-03-24T14:06:23.707] [DEBUG] Websockets - Pinging client with ConnectionId(37bdd08f-fbc4-4618-9b42-d6689833d7fd) of User UserId(student/1)}
[2023-03-24T14:06:23.708] [DEBUG] Websockets - Received pong from ConnectionId(37bdd08f-fbc4-4618-9b42-d6689833d7fd) of user UserId(student/1)}
```

fix: heroku killing idle websocket connections

---

common/match/pool.ts

I think it makes sense to already deactivate the interest confirmations now so that we have a smaller backlog of pending interest confirmations when pupil screening starts.

Turn off interest confirmations for the Lern-Fair Now Pool

---

jobs/periodic/sync-to-webflow/diff.spec.ts
jobs/periodic/sync-to-webflow/diff.ts
jobs/periodic/sync-to-webflow/index.ts
jobs/periodic/sync-to-webflow/sync-courses.ts
jobs/periodic/sync-to-webflow/sync-lectures.ts
jobs/periodic/sync-to-webflow/webflow-adapter.ts

The Webflow slug is used to identify a specific CMS item and is also used for the URL to show the detail page. For example:
```
https://lern-fair-new.webflow.io/single-course/<slug>
```
Currently, the slug is a hash of the data, which means that the link to the details page will change with every small adaptation of the course. To support static links, we should use the database ID instead. However, in order to do that, we also need to support patch requests because delete/create won't work if the items have the same slug.

Use dbid as webflow slug

---

jobs/periodic/sync-to-webflow/sync-courses.ts

We want to show conditional elements based on the open slots like "ausgebucht" or "weniger als 5 Plätze verfügbar".
Unfortunately, Webflow doesn't support calculations like max-current in these cases, so we have to do it during the sync.

add open slots to webflow courses

---

web/setupLogger.ts

Right now, most of the logs are multi-line, which decreases the visibility in our monitoring services. Therefore, we should format them as json, so that every log will be represented in a single line.
With this PR a log line will look like that:
```
{"startTime":"2023-04-06T19:00:03.381Z","categoryName":"default","data":[],"level":{"level":20000,"levelStr":"INFO","colour":"green"},"context":{},"pid":88324,"message":"Server listening on port 4000"}
```

write json formatted logs in non dev environments

---

common/student/registration.ts
common/user/roles.ts
graphql/me/mutation.ts
graphql/roles.ts
integration-tests/screening.ts
integration-tests/user.ts

We recently introduced new UIs for users that "want to be tutor / instructor / ..." but were not yet screened.
I think these should be separate roles going forward (we currently use `student { canRequestMatch canCreateCourse }` to detect this). 
As a bonus we do not need another request on the Matching or Tutoring Tab in the User-App and can just take the roles from the user session. That should make loading these tabs a lot smoother. 
<sub>[Inspired by the Spice Girls](https://www.youtube.com/watch?v=gJLIiF15wjQ): _If you wanna be a tutor, you have to be screened..._</sub>

Wannabe Roles

---

app.json

THe free Hobby Dev plan was discontinued, we now need to pay for review apps (c.f. https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq)

Switch from Postgres Hobby Dev to Mini for Review Apps

---

common/notification/notification.ts

I wasn't able to add a hook to a notification because the notificationUpdate endpoint [feeds an object of type `NotificationUpdateInput` into `Notification.update`](https://github.com/corona-school/backend/blob/02468d7f7159ffbabaf8fad15e6404e2db8b28c4/graphql/notification/mutations.ts#L79), but `Notification.update` expects a `Notification`.

Adjust type of notification object in Notification.update function

---

common/student/screening.ts

As cancelling the CoC reminders invokes the cancel-remission-request hook we have to create the remission request *after* cancelling preexisting CoC reminders in `scheduleCoCReminders`

Fix order in which existing CoC reminders are cancelled and remission requests are created

---

common/remission-request/index.ts
common/student/screening.ts

Prisma throws in the cancel-remission-request hook if no remission request exists, thus failing the entire cocCancel notification. Thus, deleteMany should be used as it deletes an arbitrary amount of remission requests.

Fix cancel coc hook delete -> deleteMany

---

common/logger/logger.ts
common/session/index.ts
graphql/authentication.ts
graphql/context.ts
graphql/index.ts
graphql/logging.ts
graphql/me/mutation.ts
graphql/pupil/mutations.ts
graphql/roles.ts
graphql/student/mutations.ts
graphql/user/fields.ts
graphql/user/mutations.ts
web/index.ts

Introduces the concept of a Session (i.e. a User-App Session) with multiple Transactions (i.e. GraphQL Queries) and uses AsyncLocalStorage to retain the transaction across continuations. The transactionID is attached to every log line to better trace logs across components.
resolves https://github.com/corona-school/project-user/issues/702

Session Logging

---

graphql/authorizations.ts
graphql/pupil/fields.ts
graphql/student/fields.ts

Introduce the concept of "entity roles" that are evaluated per entity, cache the role once it was evaluated (so that it can be reused when checking permissions for multiple field resolvers on the same entity). Also add the `@ImpliesRoleOnResult` decorator to skip entity role checks when the role is already clear from the context.
-----
When querying:
```gql
query { 
me { 
pupil { 
subcoursesJoined { # imply role on result
otherParticipants { firstname } # check role from cache
} 
} 
}
}
```
The average response time drops from **35ms to 15ms** as a lot of entity role checks can be skipped ([details](https://github.com/corona-school/backend-loader))

Entity roles

---

graphql/logging.ts

Logging every error separately helps us to filter & investigate them.
Right now, it's neither possible to show them as column nor to create a filter in the [DD UI](https://app.datadoghq.eu/logs?query=env%3Aproduction%20service%3Aweb.1%20-%40categoryName%3Aaccess%20message%3A%22Expected%20Errors%20occurred%22%20&cols=%40level%2C%40categoryName%2Cmessage&event=AgAAAYh6zBcnru61IQAAAAAAAAAYAAAAAEFZaDZ6QmhkQUFDVlZlR0Fvemd5OFFBRAAAACQAAAAAMDE4ODdhZDQtOGY0Zi00YzMzLTg4OGItZDY1MmNlYWRmNGJk&index=%2A&messageDisplay=inline&saved-view-id=78591&stream_sort=desc&viz=stream&from_ts=1685687137580&to_ts=1685687515924&live=false)
AFAICS most of the logs do not have multiple errors attached, so it should not increase the log volume.

refactor: update Expected error occoured logs

---

common/certificate/index.ts
web/server.ts

Before [the refactoring](https://github.com/corona-school/backend/pull/649/files#diff-207067d922cabc071c9988d0ebf291435c4e32db3f91abf878e985aa9f40b2bdL142-L146) we've generated the confimation page directly. 
This changed to having a redirect to the API, which was not keeping the query parameters, like `ctype=remission`. This broke the endpoint, because it wasn't able to figure out which kind of certificate to check.

fix: keep query parameters during remission redirect

---

web/server.ts

resolves https://github.com/corona-school/project-user/issues/759
The app names schema is lernfair-user-app-(...) however the pipeline is still named user-app, and review apps are prefixed by the pipeline name.

Fix CORS for review apps

---

graphql/error.ts
graphql/logging.ts

Unfortunately, the didEncounterErrors hook doesn't have a lot of information about which kind of errors did happen. This means, that it's alsomost impossible to distinguish them and decide which to log how.
Therfore, I moved the logging to the formatError hook, because the given error is always wrapped into a class with context, like ValidationError. This helps us to devide when to log what.

feature: move GraphQL error logging to formatError

---

jobs/periodic/sync-to-webflow/sync-courses.ts

To filter out old courses in the UI, we have to know when the last lecture will happen. Theoretically, we are deleting the course when they are over, but unfortunately webflow has to publish the complete side to apply the delete.

feature(webflow): add endingdate to course CMS

---

common/appointment/get.ts
graphql/user/fields.ts
integration-tests/appointments.ts

- enhanced pagination to be able to get skip values
- added edges to get if a user has appointments and the last appointment id present

fix: appointment pagination and managing empty states in FE

---

common/migration/1687941994171-updateInstructorScreeningEnumType.ts

Follow up of [this pr](https://github.com/corona-school/backend/pull/684/files#diff-3c1eda158e747f9172dc1aacd07b21a3f087105ba55efda93d86ce0787f6aadeR1-R23) to rename the instructor screening enum values as well.

fix(migration): change instructor_screening_jobstatus_enum values to match prisma

---

graphql/error.ts

This will make debugging easier as users will get the proper error message as response.

fix: expose graphql validation/user input errors

---

graphql/statistics/fields.ts

as it expects *full* UTC strings or date objects:

Fix: Use date objects in prisma stats queries 

---

common/zoom/zoom-scheduled-meeting.ts

**Description**
The date of the last appointment that was created is always set to '02:00' on the next day.
**What was done?**

fix: last appointment date

---

graphql/statistics/fields.ts

[Prisma expects template variables to appear without any quotes](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#considerations). Also, apparently the enum is only represented by ordinal numbers in the database, so we have to convert the TS enum values to the DB values. Also, Prisma doesn't seem to support `distinct` in queries (even though the types say so), so I had to change all queries using it to raw queries...

Fix: Enum handling in pupilScreenings query and distinct counting and bucket logic

---

common/appointment/get.ts

Appointments from unpublished subcourses should not be displayed on the appointment tab.

feat: filter for unpublished subcourse appointments

---

common/appointment/get.ts

Currently, match appointments don't appear in the FE appointment list and also not on the dashboard.

quickfix: get also match appointments

---

jobs/periodic/sync-to-webflow/queries.ts

Cancelled courses should not be synced to webflow.

fix: remove cancelled lectures from webflow sync

---

common/chat/helper.ts
common/notification/actions.ts
web/controllers/chatNotificationController/index.ts
web/controllers/chatNotificationController/types.ts
web/controllers/chatNotificationController/util.ts
web/server.ts

A user should get notifications from Lern-Fair if the user missed some chat messages

feat: notifications for missed chat messages

---

common/websocket/index.ts

Probably caused no real world issues as users are connected with one Websocket only anyways.

Fix weird 'for await' with early exit in Websockets

---

package.json
release.sh

Current logs from staging:
```
2023-08-01T05:11:00.298888+00:00 heroku[release.1601]: State changed from starting to up
2023-08-01T05:11:03.178166+00:00 app[release.1601]:
2023-08-01T05:11:03.178190+00:00 app[release.1601]: > corona-school-backend@0.3.0 heroku:release
2023-08-01T05:11:03.178190+00:00 app[release.1601]: > ./release.sh
2023-08-01T05:11:03.178190+00:00 app[release.1601]:
2023-08-01T05:11:03.188549+00:00 app[release.1601]: Non-Productive Deployment, setting up DB with seeded data
2023-08-01T05:11:03.498861+00:00 app[release.1601]:
2023-08-01T05:11:03.498881+00:00 app[release.1601]: > corona-school-backend@0.3.0 db:setup
2023-08-01T05:11:03.498882+00:00 app[release.1601]: > psql "$DATABASE_URL" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
2023-08-01T05:11:03.498882+00:00 …
```

fix: execute db:reset-hard so that db:seed works on staging

---

graphql/subcourse/mutations.ts

Resolves https://github.com/corona-school/project-user/issues/741
**Open Questions:**
What differentiates a subcourse from a focus course technically? Because Tobias doesn't want to automatically promote focus courses so we would need to filter them out.
What do you think of this:
> The only thing you could consider for manual course promotions would be to write to people who have not yet been contacted instead of the same or random. But that's more of a nice-to-have, not a hard requirement.
This would require a separate database table keeping track of which pupils were already contacted about a newly published course, right?

feat: automatic course promotion on publishing

---

common/notification/actions.ts
graphql/error.ts

Apparently non GraphQLErrors arrive in isUnexpectedError, we probably need to fix the type, but as a hotfix classify those as unexpected.
Also add missing sampleContexts that were forgotten.

HOTFIX: Fixups for previous hotfixes

---

common/secret/token.ts
common/user/email.ts
graphql/authentication.ts
integration-tests/auth.ts

- Make test idempotent
- Prohibit users to change their email to the email of another user, to avoid account collision during login
- Also avoid account collision with screener accounts

Various fixes to E-Mail Change

---

common/notification/messages.ts

When changing backend logic, sometimes the available variables change, and we only validate the current backend logic against the currently created notifications. Thus concrete notifications that were sent from the old backend logic and persisted in the database might not match the current templates. To avoid that this messes up the user-app, we silently ignore these instead (and just log backend errors for the tech-team to handle).

HTOFIX Ignore Message Rendering Errors

---

graphql/logging.ts

If we have syntax errors, requestContext.operation is not set, and we would fail with Internal Server Error ...

fix: Proper response in case of Syntax Errors

---

common/appointment/get.ts

We had the problem, that we only filtered for appointments for published subcourses in the frontend. So the button to load old appointments never disappear because we receive appointments from the BE from subcourses that arent published yet.

fix: filter appointments from published subcourses

---

jobs/scheduler.ts

I had to add an additional layer to properly create/maintain traces
// This function is just a wrapper to bind a new span.
// The additional layer is needed, so that we open a new span everytime the job is executed.
// Otherwise, we would only open one span in the beginning, which would generate a huge trace of multiple hours.

fix(jobs): add proper tracing to cronjobs

---

common/logger/tracing.ts
common/notification/index.ts

This will help us to understand how many reminders have been sent within a specific trace.
The idea is to filter out the ones with a certain amount of reminders and build some distribution charts with the rest.

feature: add reminder cnt to job trace

---

common/notification/actions.ts
common/pupil/screening.ts

This allows as to cancel screening reminders once a screening happened - even if a decision is felt later by the screening team
resolves https://github.com/corona-school/project-user/issues/865

feat: Action for Screening dispute

---

common/appointment/cancel.ts
common/courses/states.ts

Every subcourse has one last appointment, thus cancelling a subcourse will always fail.

fix: Subcourse cancellation

---

common/match/request.ts

Pupils with an active Match cannot request another one.

fix: Reenable Match Request Limit

---

common/courses/participants.ts
graphql/subcourse/mutations.ts

Otherwise code that doesn't go through the GraphQL layer, i.e. filling a course, does not properly add the pupils to chat & appointments.

fix: Move addGroupAppointmentsParticipant and addParticipant to commons

---

README.md
common/courses/certificates.ts
common/match/pool.ts
common/util/pdf.ts
package-lock.json
package.json

Without these the dependencies the majority of the Backend still works (so good enough for most development tasks), but the installation is way easier (especially on Windows or M2 devices).
All dependencies take about 700MB of disk space, without optional dependencies it's 480MB.
There is the risk that inside of Heroku installation fails, and then we run into runtime errors when the dependency is not there. But I guess that risk is rather low, especially as the dependencies rarely change and we also test for them in the integration tests.

build: Make Matching Algo & PDF Rendering optional

---

common/appointment/create.ts
common/appointment/participants.ts
common/appointment/update.ts
common/courses/states.ts
common/zoom/authorization.ts
common/zoom/scheduled-meeting.ts
common/zoom/util.ts
graphql/appointment/mutations.ts
graphql/subcourse/mutations.ts
graphql/util.ts
integration-tests/07_course.ts
integration-tests/08_appointments.ts
integration-tests/base/mock.ts

- Create one Zoom Meeting for each Appointment (instead of one per Course), this makes lifecycle management easier
- Changing Subcourse Instructors adapts Zoom Meeting Hosts
- Cache Zoom Access Tokens per Scope, synchronize their creation
- Add Mutation for manually creating Zoom Meetings for an Appointment

fix: scheduled appointment meetings

---

common/websocket/index.ts

The Websocket Service is only used for In App Notifications, so if there is some error nobody cares.
Also all errors we logged so far where random connectivity issues, so nothing that should raise an error

fix: Change Websocket Errors to Info

---

common/chat/contacts.ts

Fixing [this error.](https://app.datadoghq.eu/logs?query=env%3Aproduction%20-%40categoryName%3Aaccess%20status%3Aerror%20service%3Abackend-api%20&cols=%40level%2C%40categoryName%2C%40context.session%2Cerror.message%2Cmessage&event=AgAAAYqEY-lmN4jl8wAAAAAAAAAYAAAAAEFZcUVZLXFVQUFCUDh0S0dyNmxpWndBSAAAACQAAAAAMDE4YTg0NjgtMWQ3MS00YzVhLWJhMTgtZmNhYzgxMGVkODRh&index=%2A&messageDisplay=inline&refresh_mode=paused&saved-view-id=78593&sort=time&stream_sort=desc&viz=stream&from_ts=1694435748089&to_ts=1694439380191&live=false)
```
TypeError: matchContacts is not iterable
```
Sometimes I don't know why typescript doesn't complain about such inconsistencies. Undefined is a pain.

fix(chat): prevent error in case of screener

---

graphql/appointment/mutations.ts

I believe this was removed before the refactoring, and was then accidentally added during the refactoring

fix: Remove Duplicate Notifications

---

common/logger/metrics.ts
graphql/files.ts

This will help us to take informed decisions about the file storage size. It allows to monitor the usage as well as the actual size on disk.
It might help to prevent failures like [this one.](https://app.datadoghq.eu/logs?query=issue.id%3Af5cd45fe-637c-11ee-bcd4-da7ad0900005%20&cols=service%2Cmessage%2C%40context.sessionID&event=AgAAAYr_5aen5Xx6CAAAAAAAAAAYAAAAAEFZcl81YWpZQUFDaWFUUy14NGQ4YWdBQwAAACQAAAAAMDE4YjAwOGQtZmE0ZC00Yjc5LTlmYjEtMjBhMmRmYzU0NTRm&index=&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1696509657749&to_ts=1696510506303&live=false)

feature: add file storage metrics

---

common/notification/channels/mailjet.ts
common/notification/index.ts
common/notification/types.ts
graphql/concrete_notification/fields.ts

https://github.com/corona-school/project-user/issues/479
With this we can create a Notification like this:
```
{
sample_context: {
customMailjetTemplateID: "MUST_BE_SET",
},
description: "Custom Mailjet Campaign"
}
```
and then one can create a Campaign in Retool that sends out this custom template.

feat: Custom mailjet templates for campaigns

---

common/achievement/bucket.ts
common/achievement/create.ts
common/achievement/evaluate.ts
common/achievement/index.ts
common/achievement/metric.ts
common/achievement/types.ts
common/achievement/util.ts
graphql/user/mutations.ts

closes https://github.com/corona-school/project-user/issues/1019
What was done:
1. Added a GenericBucketConfig type to determine between different bucket types for different use cases
2. added a bucket to filter actions by a certain action name. This is determined weather to use ore not to use it
3. createAchievement was unified for sequential and tiered achievements
4. different bucket creators for evaluation bucket kinds
5. sort algorithm to sort templates by groups

feat: evaluation of tiered achievements

---

graphql/course/mutations.ts
graphql/match/mutations.ts
graphql/subcourse/mutations.ts
linter/graphql-undeferred-impossible.js

```
This suggests a programming mistake:
@AuthorizedDeferred(Role.INSTRUCTOR)
...
await hasAccess(course1);
```
This suggests the intent was to check access specific to a course, yet the access check is on generic roles. Usually one actually wants to use Role.OWNER instead

fix: Prohibit usage of AuthorizedDeferred without context dependent roles

---

setup.sh

Apparently they switched their default server authentication mechanism.

ci: Add Github's Post Quantum Crypto Keys

---

web/server.ts

The default limit of 100kB is too small for our campaign tool. 10MB shouldn't be too heavy.

fix: Allow larger GraphQL Requests

---

jobs/execute.ts

If the DB transaction succeeded we know if another job is running or not and can abort / continue accordingly.
If the transaction was rolled back by the DB due to a deadlock, we do not know if two transactions on the same job name collided or unrelated transactions collided (due to limitations in Postgres deadlock detection). Thus in that case it makes sense to retry, as usually one concurrent transaction should be aborted, so if we try again there should be no concurrent transaction

fix: Retry Lock if rolled back by DB

---

.env.integration-tests
.env.integration-tests.debug
common/notification/README.md
common/notification/index.ts
common/notification/messages.ts
common/notification/types.ts
integration-tests/12_notifications.ts
integration-tests/base/notifications.ts

resolves https://github.com/corona-school/project-user/issues/479
- Adds overrideType to change the type for a concrete notification, to be used by campaigns
- Adds various comments and documentation
- Adds integration tests for the notification system
- Removes the workaround for notification preferences stored as strings

feat: Campaign Type Overrides + Documentation + Tests

---

common/chat/conversation.ts
common/chat/deactivation.ts
common/chat/types.ts
graphql/chat/fields.ts
graphql/chat/mutations.ts
graphql/match/fields.ts
graphql/subcourse/fields.ts
jobs/periodic/flag-old-conversations/index.ts

I currently have no clue why the background job sometimes wrongly deactivates chats. Thus to get a better idea, expose Chat information via GraphQL so that we can look into it. Also provide mutations for manually activating and reactivating chats, if manually reactivated the deactivation job will ignore it.

feat: Expose Chat Information via GraphQL, Allow Admins to activate / deactivate Chats

---

common/slack/blocks.ts
jobs/slack-statistics.ts

For some reason Slack only allows 10 entries per table. Thus we just split them into multiple tables with empty headline :/

fix: Slack Table Generation

---

jobs/slack-statistics.ts

- Only show published courses
- Fix count shown as "[Object object]"

fix: Slack Statistics

---

graphql/authentication.ts
graphql/me/mutation.ts
graphql/roles.ts

Hidden behind a feature toggle for now, so that we can test it properly on dev (and switch it off quickly again)
https://github.com/corona-school/project-user/issues/972

feat: Require Pupil Screening

---

graphql/roles.ts

We use matches / course participation to exlude existing active pupils from needing a screening

feat: Exclude existing pupils from requiring a screening

---

web/controllers/chatNotificationController/index.ts
web/controllers/chatNotificationController/util.ts

- Closes https://github.com/corona-school/project-user/issues/1092

fix: filter system messages from missed message notifications

---

common/achievement/create.ts
common/achievement/index.ts
common/achievement/metric.ts
common/achievement/types.ts
common/achievement/util.ts
common/courses/states.ts
common/notification/actions.ts
graphql/course/mutations.ts
graphql/subcourse/mutations.ts
seed-db.ts

- new metrics for offer course achievement
- new templates for offer course achievement
- connections to mutations

Feat: offer course template

---

common/achievement/create.ts
common/achievement/get.ts
integration-tests/15_achievements.ts
prisma/migrations/20240128110055_remove_group_and_group_order_from_user_achievement/migration.sql
prisma/schema.prisma

The "Group" and "GroupOrder" fields in the user achievement were remnants from the initial version. Once we opted for on-demand rendering, these fields became unnecessary. Moreover, the group is no longer used for identification purposes either.

Remove group from ua

---

common/achievement/create.ts
common/achievement/get.ts
common/achievement/types.ts
common/achievement/util.ts
common/courses/states.ts
graphql/course/mutations.ts
graphql/subcourse/mutations.ts
integration-tests/15_achievements.ts
prisma/migrations/20240128111430_add_relation_as_db_field/migration.sql
prisma/schema.prisma

We identify user achievements by the templateID, userID, and relation. Previously, the relation was embedded within the JSON context, making it difficult to use or query. This PR moves the relation to a dedicated field in the user achievement table, allowing for easier querying and the creation of a unique index. This ensures we avoid accidentally creating multiple achievements for the same template and relation.
It should prevent issues like this from our UAT tests, where we've created multiple achievements of the same template for the same user and relation.

feature: add dedicated relation field to user achievement table

---

graphql/statistics/fields.ts

- count registrations of helpers/pupils (instead of just tutors/tutees)
- consider both screenings and instructor_screenings in `helperScreenings` endpoint
- `nowFirstMatchesStudent` now considers all students that had their first match in a certain month; not just students that only had a single match which happens to be in that month
- `nowDissolvedMatchesAfter/BeforeThreeMonths` now considers `dissolvedAt` instead of `updatedAt`
- add category controls to `offeredLectures` and `numSubcourses`
- consider start date of first lecture for `numSubcourses`, only consider courses that are allowed
- consider start date of lectures instead of creation date in `offeredLectures`, only consider group type appointments
- split `rateSuccessfulCoCs` into tutor and instructor endpoints
- rate of …

Fix and amend statistics

---

graphql/statistics/fields.ts

Fix trend computation resulting in undefined if there are no averages to compare to (e.g. when selecting 2022-01-01 as start date, as this is also the date from which trends are computed)

Fix trend computation resulting in undefined 

---

common/chat/conversation.ts
jobs/periodic/flag-old-conversations/index.ts

- Closes https://github.com/corona-school/project-user/issues/1093
Already deactivated chats should not be requested, so we added a filter to the talkjs request.

feat: filter out deactivated chats from the cronjob

---

common/match/request.ts

If pupils have an active match, they can request another match (and need to be screened again etc.).
resolves https://github.com/corona-school/project-user/issues/1143

feat: Allow Pupils to have two matches

---

common/appointment/tracking.ts
graphql/appointment/mutations.ts
graphql/match/mutations.ts
graphql/ownership.ts
graphql/subcourse/mutations.ts
integration-tests/15_achievements.ts

We tried to abstract away courses and matches with "appointments", so in my eyes it does not make sense to now introduce "match meetings" and "course meetings" if we can also just have "appointment meetings". Also in the future we could do plausibility checks. 
This also removes the need to pass around subcourseId and matchId everywhere in https://github.com/corona-school/user-app/pull/420

refactor: Track Appointment Meeting Join

---

common/appointment/create.ts

- Closes https://github.com/corona-school/project-user/issues/1088
- works with https://github.com/corona-school/user-app/pull/474

feat: alternativ links for appointments

---

common/appointment/update.ts

If appointments get updated and an `override_meeting_link` is set (no zoom meeting id) the zoom meeting shouldn't be updated.

feat: update only zoom if zoom meeting exist

---

common/courses/notifications.ts
common/courses/states.ts
graphql/subcourse/mutations.ts

- Prevent that a course is promoted twice
- Limit the number of promotions triggered to 500
- Increase the estimated response rate, to notify less users and be less spammy

HOTFIX: Prevent double course promotions

---

common/appointment/create.ts
graphql/appointment/fields.ts

For some reason the UserApp passes in an empty string for the nullable meetingLink, as such no Zoom Meeting is created any longer for followup appointments, and users cannot join the meeting anymore.
So far affected 33 Meetings in the last 4 days
https://github.com/corona-school/project-user/issues/1150

HOTFIX: Meetings with neither Zoom nor alternative meeting Link

---

common/courses/notifications.ts
common/notification/index.ts
graphql/concrete_notification/mutations.ts
integration-tests/01_user.ts
integration-tests/13_deactivation.ts

For sure we need to allow certain mails be sent to unverified accounts, especially the mail to verify the account :) 
Also we already start sending some mails directly after the registration, I guess we might want to send them even if the account was not yet verified. Thus this introduces a grace period of 30 days where an unverified account can still get notifications, afterwards we do not send notifications anymore. Also exclude verification & password reset, just in case someone wants to regain access after these 30 days.

fix: Prohibit mails to unverified accounts, exclude unverified pupils from course promotions

---

common/achievement/create.ts

We should avoid creating a new achievement if the next step precedes the current step.
This scenario could occur, for instance, if an old student account, created before the implementation of the achievement system, applies to become an instructor.
Consequently, the screening process would trigger the creation of the Onboarding achievement, implying several steps that are inappropriate for the student.
Thus, this PR ensures that only the current or subsequent achievement steps are created, while others are automatically bypassed.

fix: don't create achievement for screening old users

---

common/appointment/cancel.ts
common/appointment/create.ts
common/appointment/participants.ts
common/appointment/update.ts
common/courses/participants.ts
common/courses/states.ts
common/notification/actions.ts

- Appointment reminders for courses are scheduled when the course is published. Thus instructors do not get reminders for unpublished courses
- Also schedule reminders when a participant or instructor joins a course, and cancel them when they leave it
- Properly only cancel the reminders belonging to a single appointment, previously it would just cancel all reminders for all appointments

feat: Defer course appointment reminders to publish, also schedule Reminders when joining a course, properly cancel them

---

common/achievement/evaluate.spec.ts
common/achievement/evaluate.ts
common/achievement/get.ts
common/achievement/index.ts
integration-tests/15_achievements.ts

Right now, streaks will be reset to not achieved even tho the evaluation result equals to the record value. (Which is expected in many cases).
So this PR, ensures that we only reset the streak if the evaluation result < record value.

refactor: achievement evaluation

---

common/notification/channels/mailjet.ts
graphql/match/mutations.ts

https://github.com/corona-school/project-user/issues/1132
https://github.com/corona-school/user-app/pull/504
- Added a new `matchReport` mutation that extracts all the needed information for the report from the given matchId. Then, it builds an email and sends it to the support team.
- Adjusted the test email mode to include the subject
I tested both flows and the final email will look something like this:

feat: Report match

---

graphql/appointment/fields.ts

https://github.com/corona-school/project-user/issues/1164
- Allow Tutors to access the `zoomMeetingUrl` field, Replaced Instructor with `Role.OWNER`
I tested it locally before and after, and now users that are tutors _but not instructors_, can access the `zoomMeetingUrl` field, meaning that the appointment detail page works again for them.

fix: Allow tutors to access zoomMeetingUrl field

---

common/notification/actions.ts
common/pupil/screening.ts
graphql/pupil/mutations.ts

https://github.com/corona-school/project-user/issues/1168
- Added the new actions
- Updated the logic to trigger these new actions _(only on their first screening)_
Tested it locally and the new actions are being executed as expected only on the first screening

Feat: Add actions for sus screening after registration

---

graphql/statistics/fields.ts

It seems like we sometimes get negative account lifetimes due to screenings that took place after the "last action" of a user. We want to ignore such results as they don't make sense.

Fix: ignore negative lifetimes

---

common/courses/notifications.ts
graphql/user/fields.ts

Exclude unscreened pupils from course promotions and campaigns
Closes https://github.com/corona-school/project-user/issues/1166.
The issue also mentions helpers, but as far as I can tell we already exclude unscreened helpers in campaigns: https://github.com/corona-school/backend/blob/19860a2694b3ad0ade309aac0cd286b87a96ffc5/graphql/user/fields.ts#L203-L207

Exclude unscreened pupils from course promotions and campaigns

---

common/transactionlog/log.ts
common/user/index.ts
integration-tests/12_notifications.ts
prisma/migrations/20240412131406_remove_wix_id_from_transaction_log/migration.sql
prisma/schema.prisma

https://github.com/corona-school/project-user/issues/1160
- Add prisma migration to drop the `user` column (aka `wix_id`) from the transaction log
- Remove todos and code referencing user column

Refactor: Remove wix id from transaction log

---

common/appointment/get.ts
graphql/match/fields.ts
graphql/user/fields.ts

- Added a firstAppointmentId resolver (based on the existing `lastAppointmentId`)
- Renamed existing `getLastAppointmentId` utility function -> `getEdgeAppointmentId `
This is related to [this frontend PR](https://github.com/corona-school/user-app/pull/521)

feature: Add firstAppointmentId resolver for match and user

---

common/user/update.ts
common/zoom/user.ts

We need to delete and recreate a Zoom user when a Lern-Fair user changes their email address, as we cannot use the changeEmail endpoint because we're not using managed domains on Zoom.

Fix: delete and recreate zoom user when changing emails

---

common/user/update.ts

Check if user has zoomUserId before recreating Zoom account on email change

Fix: check if user has zoomUserId 

---

common/zoom/user.ts

https://github.com/corona-school/project-user/issues/1192
Added a fallback to fetch users by `zoomUserId` when the email doesn't work. I decided to do this as a fallback because I saw on the zoom forum some reports of the same issue with `zoomUserId`...

fix: Add fallback when fetching zoom user by email does not work

---

common/notification/actions.ts
common/notification/hooks.ts
common/pupil/activation.ts
graphql/me/mutation.ts
graphql/pupil/mutations.ts
jobs/periodic/redact-inactive-accounts/deactivate-inactive-accounts.ts

https://github.com/corona-school/project-user/issues/1187
- Added a new action to trigger when admins/screeners deactivate a pupil account
- Added a `deactivate-pupil` hook _(Later will be attached to some notifications)_
- Added a `silent` and `byAdmin` options to the `deactivatePupil` to customize the notification behavior

Feat: SuS Screening rejection adjustments

---

graphql/subcourse/fields.ts

Little backend part for https://github.com/corona-school/project-user/issues/975
Allows to only fetch subcourses with specific courseStates with the subcourseSearch-Query.
So that the frontend doesn't have to fetch courses that it doesn't need. 
To be merged before the frontend.

feat/filter for courseStates in SubcourseSearch query

---

prisma/schema.prisma

https://github.com/corona-school/project-user/issues/1199
Added the [`@updatedAt`](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#updatedat) directive to our `updatedAt` fields.
This directive is a Prisma-level feature, so the a new migration wasn't created / needed.

fix: Add missing @updatedAt directives

---

jobs/periodic/notification-courses-ended-yesterday/index.ts

https://github.com/corona-school/project-user/issues/1213
Updated the filters on the `notification-courses-ended-yesterday` job to exclude subcourses that were cancelled, denied, not published.

fix: Add filters to get courses that were actually given

---

graphql/types/preferences.ts

Should fix the error:
```
GraphQLError: Variable \"$preferences\" got invalid value { email: true, push: true } at \"preferences.appointment\"; Field \"push\" is not defined by type \"ChannelInput\".
```
when changing preferences

fix: Add push in Channels type

---

graphql/subcourse/fields.ts

- Updated the `canPromote` resolver to return a Decision object instead of a boolean to keep consistency with the other `canXYZ` fields.

feat: Expose why a course cannot be promoted

---

common/notification/channels/push.ts
common/notification/index.ts

The client does not know whether the push subscription was already added successfully before, lets just readd it in that case

fix: Make push subscription idempotent

---

common/notification/channels/push.ts
common/notification/index.ts
common/notification/messages.ts
common/notification/types.ts

It is not so easy to establish a backend connection in the webworker - thus it seems easier to just include the whole message to show in the push notification itself. As we decrypt the message using the client key, only the client can read it - so there should be no privacy problems - as users need to trust their browsers anyways.
https://github.com/corona-school/project-user/issues/606

feat: Include message in push notification

---

jobs/periodic/sync-to-webflow/diff.spec.ts
jobs/periodic/sync-to-webflow/diff.ts
jobs/periodic/sync-to-webflow/index.ts
jobs/periodic/sync-to-webflow/sync-courses.ts
jobs/periodic/sync-to-webflow/sync-lectures.ts
jobs/periodic/sync-to-webflow/webflow-adapter.ts
utils/environment.ts

https://github.com/corona-school/project-user/issues/1203
This PR updates the webflow sync to use the new V2 API. Previously, with V1, we used a hash to determine if a record had changed. Unfortunately, with the new API structure, this would mean that all records would need to be recreated. Therefore, I've replaced the hash mechanism with a comparator to ensure that we only recreate records if it's really necessary.
Additionally, I've introduced a new dry-run environment variable to allow testing the changes before executing real actions.

feature: migrate to webflow api v2

---

common/courses/states.ts

Filter out canceled appointments when checking if a course can be published.
_(I'll merge it to test it on STG as well before releasing it)_ Please review anyway :)

fix: Filter out canceled appointments

---

graphql/authorizations.ts
graphql/course/fields.ts
graphql/course/mutations.ts
prisma/migrations/20240710090706_add_active_field_to_course_tag/migration.sql
prisma/schema.prisma

https://github.com/corona-school/project-user/issues/1270
- Added `active` field on course_tag model
- Added mutation to activate/deactivate course_tags
- Return only active tags to all users except admins

Feat: Soft delete course tags

---

common/courses/participants.ts
graphql/subcourse/mutations.ts

- If a pupil leaves a course, the course is joinable and there are pupils on the waiting list, add pupils from the waiting list
- If a course is filled by the system, do not send a notification to the instructor (either the instructor themself requested it, support did it on behalf of the instructor, or we fill the subcourse after a pupil left the subcourse, so it was full and now is full again)
resolves https://github.com/corona-school/project-user/issues/1271

fix: If pupils leave a course, add other pupils from the waiting list & Avoid annoying course instructors with notifications

---

jobs/periodic/sync-to-webflow/webflow-adapter.ts

This PR should fix the issue of old courses on the website. It will ensure that deleted collection items will be unpublished automatically.

fix: use live endpoint to remove webflow collection item

---

jobs/periodic/sync-to-webflow/webflow-adapter.ts

By definition `DELETE /items/{id}/live` is
```
Removing a published item will unpublish the item from the live site and set it to draft.
```
This is a problem as it might be published in the future again. Therefore, this PR will call `DELETE /items/{id}` afterwards to finally delete the draft.

fix: fully delete webflow collection items

---

graphql/chat/mutations.ts

https://github.com/corona-school/project-user/issues/1277
- Allow instructors to create prospect chats (Restored)

fix: Restore allow instructors to create prospect chat

---

common/match/matching.spec.ts
common/match/matching.ts
package-lock.json
package.json

Moves the Matching Algorithm to Typescript. Replaces the much more complicated minimum cost maximum flow problem with a much simpler assignment problem - solutions should be equivalent (given the same cost function).
Only introduces the new algorithm, does not yet switch to it. 
https://github.com/corona-school/project-user/issues/1316

feat: Matching in Typescript

---

common/match/matching.perf.pupil.json
common/match/matching.perf.student.json
common/match/matching.perf.ts
common/match/matching.spec.ts
common/match/matching.ts
package.json

Splits the tests into small unit tests that are fast to run (`npm run unit`) and perf tests that might take longer (`npm run perf`) - `npm run test` runs all of them in the barrier. 
Adds a performance test for the matching algorithm, which simulates a real world matching - pupils and students continously request matches, every N days the matching algorithm is run using the current pools, matched users are removed from the pool. At the end, reports how many matches are created, how many subjects and states match, and how long the pupils and students had to wait for the match.
Extends the Matching Algorithm to exclude duplicate matches (as the old implementation does). Currently implemented as a postfilter after the matching, dont think it happens often and is worth considering in the …

feat: Matching algo performance + Exclude duplicate matchings

---

common/match/matching.ts
common/match/pool.ts
package.json

resolves https://github.com/corona-school/project-user/issues/1316

feat: Switch to the new matching algorithm

---

jobs/slack-statistics.ts

Updated the Slack-statistics query to remove limitation that force all lectures to start in the current month

fix: Remove start-date limitation

---

common/appointment/update.ts

https://github.com/corona-school/project-user/issues/1303
- Remove match from declinedBy when the appointment is rescheduled

feat: Re-invite match when an appointment is rescheduled

---

common/pupil/index.ts
graphql/subcourse/fields.ts

We should return prospectParticipants as `Participant`s such that we can reuse parts of the waitinglist UI on the front end.

Fix: return full participants from prospectParticipants field

---

common/match/create.ts

In case two users are matched at the same time (e.g. through a Match run + manual matching) there is a certain likelihood that they are matched twice. By refetching the openMatchRequestCount right before creating the match, the likelihood of that happening is reduced.
There might also be a bug in the new matching that creates duplicate matches, I hope if there is one, we will find it with this change.

fix: Reduce likelihood of race condition in Matching

---

common/match/create.ts
common/notification/actions.ts
common/notification/hook.ts
common/notification/hooks.ts
common/notification/index.ts
common/util/subjectsutils.ts

- Resolves https://github.com/corona-school/project-user/issues/1275
- Resolves https://github.com/corona-school/project-user/issues/1281
- Add/Trigger new action when a DaZ match is created
- Add a hook/action to invite Instructors only users to reflection meetings after completing their very first group appointment

Feat: Add new actions for DaZ Matches and Instructors Only Users

---

common/student/screening.ts
graphql/student/mutations.ts

- Added logic to require student ethics onboarding after a successful screening
This is currently done on the frontend but it'd be better to have it on the backend. For example, screenings done on Retool do not enforce this onboarding

fix: Require ethics onboarding after screening success

---

graphql/authorizations.ts
graphql/student/mutations.ts
prisma/migrations/20241213093513_add_description_for_screening_to_student/migration.sql
prisma/schema.prisma

Added a new field `descriptionForScreening` that Student screenings use to keep general information about students across different meetings they have with them (I forgot to add this field in my previous [PR](https://github.com/corona-school/backend/pull/1163)

feat: Add student field descriptionForScreening

---

common/achievement/evaluate.spec.ts
common/match/create.ts
common/match/pool.ts
prisma/migrations/20250102153056_drop_match_source/migration.sql
prisma/migrations/20250102153441_link_match_to_matchpoolrun/migration.sql
prisma/schema.prisma

Add foreign key relationship between match and match run to track all matches that were created at once,
additionally drop Match.source as it is unused since 4 years + misleading.

feat: Cleanup match to match_pool_run relation

---

graphql/screener/mutations.ts

When creating a screener the token created lives forever which is a security problem (especially as it is shared with the user creating the screener account). Now it expires after one week, the screener should set their password in the meantime.
resolves https://github.com/corona-school/project-user/issues/1233

fix: Expire screener token

---

common/util/error.ts
common/zoom/scheduled-meeting.ts
graphql/appointment/fields.ts
graphql/appointment/mutations.ts

Resolves https://github.com/corona-school/project-user/issues/1395
Added a patch for those rare cases where Zoom doesn't recognize a `meetingId` they gave us. As explained in the ticket, we are trying to recreate a Zoom meeting only if
- The user is the owner of the appointment (?) or admin
- The appointment is not canceled
- The appointment has not yet ended
- There is a ZoomMeetingId
- Zoom doesn't recognize the ZoomMeetingId we have

fix: Invalid Zoom Meeting Id

---

common/pupil/registration.ts
graphql/authorizations.ts
graphql/types/enums.ts
graphql/types/userInputs.ts
integration-tests/01_user.ts
integration-tests/11_registerPlusMany.ts
prisma/migrations/20250107131743_add_pupil_email_owner/migration.sql
prisma/schema.prisma
seed-db.ts

Resolves https://github.com/corona-school/project-user/issues/1386
- Added a new `emailOwner` field on the pupil
- Updated pupil registration input data
- Adjusted tests & seed data

Feat: Add pupil email owner field

---

common/appointment/create.ts
common/courses/filters.ts
graphql/student/fields.ts

Resolves https://github.com/corona-school/project-user/issues/1392
- Add validation to prevent adding appointments to a cancelled course
- Add a filter to exclude cancelled courses from `subcoursesInstructing` query _(To be used in the frontend PR part of this same issue)_

Fix: Prevent creating new appointment for cancelled courses

---

common/certificate/index.ts

- only count lectures that are in the past
- add date variable so our template renders correctly
- friendly date formatting

Fix: Instant Certs: only count lectures that are in the past, add date variable, friendly date formatting

---

common/appointment/participants.ts
seed-db.ts

Resolves https://github.com/corona-school/project-user/issues/1421
- Updated `addGroupAppointmentsParticipant` to only add new participants/organizers to future lectures
- Adjusted seed data to include participants/organizers for past lectures

Fix: Add pupils to future lectures

---

common/user/index.ts
graphql/user/fields.ts

It's nice that this was considered in the UI, but is still exposed to the user at the API. If we implement 2-anonymity, let's do it all the way.

fix: Do not expose supported hours if referred users is less than 2

---

common/certificate/index.ts

- Added a default value for non-nullable field during creation

fix: Instant certificates for users without lectures

---

common/appointment/create.ts

Resolves https://github.com/corona-school/project-user/issues/1447
- change to 60 min the default ad-hoc meeting duration

feat: change to 60 min the default ad-hoc meeting duration

---

.github/workflows/node.js.yml

Resolves
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down

ci: upgrade actions packages

---

common/appointment/create.ts
common/appointment/participants.ts
common/courses/filters.ts
common/courses/participants.ts
common/transactionlog/log.ts
common/user/index.ts
common/user/roles.ts
common/zoom/scheduled-meeting.ts
graphql/authorizations.ts
graphql/student/fields.ts
graphql/subcourse/fields.ts
graphql/subcourse/mutations.ts
linter/graphql-undeferred-impossible.js
prisma/migrations/20250312104151_add_subcourse_mentors_student_table/migration.sql
prisma/schema.prisma
seed-db.ts

Partially resolves https://github.com/corona-school/project-user/issues/1428
- Added a new `subcourse_mentors_student` table where students can sign up to help on a course
- Added a new `SUBCOURSE_MENTOR` role
- Added mutations to allow students to join/leave courses that allow mentors _(only the Hausaufgabenhilfe for now)_
**Notes:**
- Mentors don't have edition rights over the course/subcourse
- The role isn't tied to having a specific screening
- Mentors can join/leave a course
- Mentors don't count as subcourse participants (only those who are learning do)
- Mentors don't auto-join the course chat / shouldn't receive notifications about the course. As this is mainly targeted at integrating the Hausaufgabenhilfe, the communication for that is for now handled a bit differently

Feat: Integrate students in the Hausaufgabenhilfe

---

common/achievement/evaluate.spec.ts
common/appointment/tracking.ts
graphql/authorizations.ts
prisma/migrations/20250314151207_add_joined_by_column_to_the_lecture_table/migration.sql
prisma/schema.prisma

Resolves https://github.com/corona-school/project-user/issues/1456
- Add a new `joinedBy` column in the `lecture` table
- Update the `trackUserJoinAppointmentMeeting` function to save when a user joins an appointment

Feat: Track appointments attendance

---

common/zoom/scheduled-meeting.ts
common/zoom/user.ts
graphql/appointment/fields.ts

Resolves https://github.com/corona-school/project-user/issues/1460
- Added a resolver for the Zoom meeting password. This will be used on our Zoom component view on the frontend
- Included the Meeting password (if any) in the `zoomMeetingUrl` resolver
In the meantime, I changed the settings again to not require a password since this feature wasn't built with that in mind so I'm not sure what other things it could break. 👀.
All of this is pretty weird. The only thing I could find was this post https://devforum.zoom.us/t/passcode-wrong-error/59739, but it wasn't entirely clear why it happened

Hotfix: Expose Zoom Meeting Password

---

prisma/migrations/20250325183301_remove_project_matching_and_experts/migration.sql

- Recreated the `remove_project_matching_and_experts/migration.sql` migration to include the latest changes _(In the [original PR](https://github.com/corona-school/backend/pull/869), I didn't do this, and this may be the root cause of it failing on prod)_

fix: Recreate migration

---

common/student/screening.ts
graphql/student/mutations.ts
graphql/types/enums.ts
prisma/migrations/20250407094956_add_student_screening_status_enum/migration.sql
prisma/schema.prisma
seed-db.ts

The backend part of https://github.com/corona-school/project-user/issues/1464
- I added a new `status` column to the `screening` / `instructor_screening`, which is similar to how we do with the pupil screenings. This will allow for student screenings in pending or in missed statuses.
- Update mutations to start saving infos there. For now, only `success` / `rejection`
[Hier I wrote a query to populate this column for the existing screenings based on the `success` column](https://github.com/corona-school/dev-db/commit/2bacce1929203fcabf663371a529f40c98d844a5) (which will be deprecated/removed in future PRs)

feat: Add status column to students screenings

---

.github/workflows/node.js.yml
seed-db.ts

- Enable newsletter by default for some of our test users on STG
- Initially not expected but: Also upgraded the Ubuntu version used in the actions since the one we were using was unsupported and the checks weren't running at all

Chore: Enable newsletter by default / Upgrade Ubuntu Version

---

common/match/pool.ts

It turns out that if you specify multiple `NestedStringFilter`s inside the `not` filter, they get ORed instead of ANDed.
Previously we had `viable = !(startsWith("test") || endsWith("@lern-fair.de"))` = `!startsWith("test") && !endsWith("@lern-fair.de")`
We want: `viable = !(startsWith("test") && endsWith("@lern-fair.de")` = `!startsWith("test") || !endsWith("@lern-fair.de")`.

Fix logic in matching getViableUsers for test.*@lern-fair.de accounts

---

seed-db.ts

- Added 10 more empty courses to match a bit better the current state of production (`courseId` != `subcourseId`)

chore: Add more empty courses

---

common/match/create.ts
common/match/dissolve.ts
common/match/request.ts
common/notification/hooks.ts
prisma/schema.prisma

Resolves https://github.com/corona-school/project-user/issues/1477
Updated when we invalidate pupil screenings.
- **Before:** After a match is created / a Pupil match request is revoked
- **After:** When a HuH dissolves a match due to Ghosting / Personal Issues, OR if the last successful screening is older than 4 months _(calculated at time of requesting a new match)_

Feat: Update when to invalidate pupil screenings

---

.env.example
common/calendly/index.ts

Resolves https://github.com/corona-school/project-user/issues/1487
- Added a filter to prevent events not related to screenings from triggering the webhook logic.
- Documented new env variables

feat: Filter Calendly events that trigger the webhook logic

---

common/appointment/get.ts

We don't want to show the new screening appointments in the UI for now. This will be tackled in a separate task

feat: Exclude screening appointments from queries

---

common/student/screening.ts

Updated when we require student onboarding to be done before the screening is approved

fix: Adjust when to require for ethics onboarding

---

common/calendly/index.ts

- I added a missing handler in case the user from the Calendly event is not found.

fix: Handle user retrieval error in invitee created event

---

common/achievement/evaluate.spec.ts
common/match/create.ts
common/match/util.ts
graphql/match/fields.ts
prisma/migrations/20250606074613_add_subjects_information_on_match_table/migration.sql
prisma/schema.prisma

https://github.com/corona-school/project-user/issues/1482 (Partially)
- Added a `subjectsAtMatchingTime` on the match table
- Adjusted the getOverlappingSubjects function to include the grade range from `studentSubject`
- Use the new property on the subjectsFormatted resolver when available

Feat: Save subjects information on match table

---

common/calendly/index.ts
graphql/pupil_screening/fields.ts

Resolves https://github.com/corona-school/project-user/issues/1501
- Added a validation to prevent multiple active Calendly events
- Allow obtaining appointments from disputed screenings
- Allow obtaining only ongoing appointments or in the future

Fix: Keep one active Calendly event

---

common/util/calendarPreferences.ts
graphql/authorizations.ts
graphql/match/fields.ts
graphql/me/mutation.ts
graphql/pupil/mutations.ts
graphql/student/mutations.ts
graphql/types/calendarPreferences.ts
graphql/user/fields.ts
prisma/migrations/20250619125253_add_calendar_preferences/migration.sql
prisma/schema.prisma
seed-db.ts

The initial backend part of https://github.com/corona-school/project-user/issues/1497
- Added a new `calendarPreferences` column in the `student`/`pupil` tables
- Updated the updateX mutations to allow this new property
- Updated the seed script to include default calendar preferences for our test users.
- Added a new resolver for the matchAvailability from the perspective of the current user.

Feat: Calendar preferences

---

common/match/matching.spec.ts
common/match/matching.ts
common/util/calendarPreferences.ts
graphql/types/calendarPreferences.ts

https://github.com/corona-school/project-user/issues/1499
- Added a function to get the amount of overlapping hours from two availabilities
- Updated the matching algo to consider calendar availability
- Updated tests

Feat: Include calendar preferences in matching algo

---

graphql/subcourse/fields.ts

Add a resolver for subcourse mentors. This is required for the new course creation page.

Add resolver for subcourse's mentors

---

common/appointment/participants.ts
common/appointment/util.ts
graphql/subcourse/fields.ts
graphql/types/enums.ts

Resolves https://github.com/corona-school/project-user/issues/1520 _(Frontend PR would follow if this solution is fine)_
- Adjusted the addGroupAppointmentsOrganizer logic to remove new organizer from future lectures as participant and add it as organizer
- Updated the joinedAppointment resolver to include an `as` parameter to get appointments where I'm instructor or participant

Fix: Mentors to instructors adjustments

---

common/appointment/update.ts
common/zoom/scheduled-meeting.ts
integration-tests/07_course.ts
integration-tests/08_appointments.ts

Resolves https://github.com/corona-school/project-user/issues/1522
- Updated the `updateZoomMeeting` so it doesn't break all the Zoom appointments for a course after adding/removing an instructor.
- Fix the reschedule functionality so it actually reschedules the meeting in Zoom and it doesn't get deleted by them

Hotfix: Zoom mess

---

common/match/pool.ts

Fixed error `Float cannot represent non numeric value: Infinity`When visiting statistics page on Retool

fix: Validate demand field
